import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'az' | 'en' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  az: {
    // Common
    'common.back': 'Geri',
    'common.next': 'İrəli',
    'common.cancel': 'Ləğv et',
    'common.save': 'Yadda saxla',
    'common.delete': 'Sil',
    'common.edit': 'Redaktə et',
    'common.viewAll': 'Hamısına bax',
    'common.viewMore': 'Daha çox bax',
    'common.close': 'Bağla',
    'common.cart': 'Səbət',
    'common.profile': 'Profil',
    'common.per': 'vahidə',
    'common.comingSoon': 'Tezliklə',
    'common.more': 'daha',
    'common.saved': 'Yadda saxlanıldı',
    'common.editProfile': 'Profili redaktə et',
    'common.demoUpdated': 'Demo məlumatı yeniləndi',
    'common.detailsOpened': 'Detallar açıldı',

    // Customer Home
    'customer.home.title': 'KəndYol',
    'customer.home.freshFromFarm': 'Fermadan təzə məhsullar',
    'customer.home.nextDelivery': 'Növbəti çatdırılma',
    'customer.home.orderCutoff': 'Sifariş üçün qalan vaxt:',
    'customer.home.hours': 'Saat',
    'customer.home.minutes': 'Dəqiqə',
    'customer.home.seconds': 'Saniyə',
    'customer.home.saveUpTo': 'Qənaət',
    'customer.home.vsRetail': 'mağazadan ucuz',
    'customer.home.farmFresh': 'Təzə məhsul',
    'customer.home.daysOld': 'gün əvvəl yığılıb',
    'customer.home.directFrom': 'Birbaşa',
    'customer.home.ruralFarms': 'kənd fermalarından',
    'customer.home.subscriptionBoxes': 'Abunə paketləri',
    'customer.home.browseByShelfLife': 'Saxlanma müddətinə görə',
    'customer.home.activeOrder': 'Aktiv sifariş',
    'customer.home.orderInTransit': 'Sifarişiniz yoldadır',
    'customer.home.arriving': 'Çatdırılma:',

    // Browse Products
    'browse.title': 'Məhsullara bax',
    'browse.searchPlaceholder': 'Məhsul axtar...',
    'browse.allProducts': 'Hamısı',
    'browse.available': 'məhsul mövcuddur',
    'browse.inCart': 'Səbətdə',
    'browse.per': 'vahidə',
    'browse.days': 'gün',
    'browse.farmer': 'Fermer',

    // Product names & farms
    'product.organicTomatoes': 'Pomidor',
    'product.freshSpinach': 'Təzə ispanaq',
    'product.freeRangeEggs': 'Kənd yumurtası',
    'product.sweetPeppers': 'Şirin bibər',
    'product.freshButter': 'Təzə yağ',
    'product.potatoes': 'Kartof',
    'product.strawberries': 'Çiyələk',
    'product.cucumbers': 'Xiyar',
    'product.bunch': 'dəstə',
    'product.dozen': 'düjün',
    'product.piece': 'ədəd',
    'product.kg': 'kq',

    // Cart
    'cart.title': 'Səbətiniz',
    'cart.nextDelivery': 'Növbəti çatdırılma: Çərşənbə, 25 Mart',
    'cart.orderCutoff': 'Sifariş son tarixi: Bazar ertəsi 23:59 (23s 45d qalıb)',
    'cart.items': 'Məhsullar',
    'cart.deliveryMethod': 'Çatdırılma üsulu',
    'cart.pickup': 'Götürmə nöqtəsi (Tövsiyə olunur)',
    'cart.pickupDesc': 'Ən yaxın mərkəzdən götürün',
    'cart.free': 'Pulsuz',
    'cart.homeDelivery': 'Evə çatdırılma',
    'cart.homeDeliveryDesc': '₼45-dən aşağı sifarişlər üçün ₼4. ₼45+ sifarişlərdə pulsuzdur.',
    'cart.savings': 'Sizin qənaətiniz',
    'cart.savingsDesc': 'Mağaza qiymətlərindən ucuz - toplu çatdırılma sayəsində!',
    'cart.subtotal': 'Aralıq cəm',
    'cart.delivery': 'Çatdırılma',
    'cart.retailPrice': 'Mağaza qiyməti',
    'cart.yourSavings': 'Sizin qənaətiniz',
    'cart.total': 'Cəmi',
    'cart.checkout': 'Sifarişi tamamla',
    'cart.empty': 'Səbətiniz boşdur',
    'cart.emptyDesc': 'Başlamaq üçün təzə məhsullar əlavə edin',
    'cart.browseProducts': 'Məhsullara bax',
    'cart.customize': 'Fərdiləşdir',
    'cart.youSaving': 'Siz ₼{amount} qənaət edirsiniz',

    // Subscription boxes
    'boxes.vegetable': 'Tərəvəz paketi',
    'boxes.dairy': 'Süd məhsulları',
    'boxes.meat': 'Ət paketi',
    'boxes.custom': 'Özünüz seçin',
    'boxes.items': 'məhsul',
    'boxes.yourChoice': 'Sizin seçiminiz',
    'boxes.kg': 'kq',

    // Subscriptions
    'sub.title': 'Abunəliklər',
    'sub.active': 'Aktiv',
    'sub.available': 'Mövcud paketlər',
    'sub.noActive': 'Aktiv abunəlik yoxdur',
    'sub.noActiveDesc': 'Müntəzəm çatdırılma üçün bir pakete abunə olun',
    'sub.browseBoxes': 'Paketlərə bax',
    'sub.weekly': 'Həftəlik',
    'sub.nextDelivery': 'Növbəti çatdırılma',
    'sub.week': 'həftə',
    'sub.included': 'Daxil olan məhsullar:',
    'sub.customizeTitle': 'Paketi fərdiləşdir',
    'sub.customizeDesc': 'Növbəti çatdırılma üçün paketdə qalacaq məhsulları seçin.',
    'sub.customizeHint': 'Ən azı bir məhsul seçilməlidir.',
    'sub.customizeSaved': 'Paket fərdiləşdirildi',
    'sub.activeStatus': 'Aktiv abunəlik',
    'sub.paused': 'Dayandırılıb',
    'sub.whySubscribe': 'Nə üçün abunə olmalısınız?',
    'sub.benefit1': 'Birtəfəli alışlardan 30%-ə qədər qənaət edin',
    'sub.benefit2': 'Heç vaxt təzə məhsul bitməsin',
    'sub.benefit3': 'Müntəzəm sifarişlərlə yerli fermerləri dəstəkləyin',
    'sub.benefit4': 'İstənilən vaxt dayandırın və ya ləğv edin',
    'sub.subscribeNow': 'İndi abunə ol',
    'sub.nextBatch': 'Növbəti toplu çatdırılma',
    'sub.nextBatchDesc': 'Abunəlik məhsullarınız Çərşənbə çatdırılmasına daxil ediləcək',
    'sub.cutoff': 'Sifariş son tarixi: Bazar ertəsi 23:59',
    'sub.delivery': 'çatdırılma',
    'sub.savings': 'qənaət',
    'sub.flexible': 'Çevik qiymət',
    'sub.status.active': 'Aktiv',
    'sub.status.paused': 'Dayandırılıb',
    'sub.cancel': 'Abunəliyi ləğv et',
    'sub.cancelTitle': 'Abunəliyi ləğv et',
    'sub.cancelConfirm': 'Əminsiniz?',
    'sub.cancelDesc': 'Bu abunəliyi ləğv edəcək. Növbəti ödəniş tutulmayacaq.',
    'sub.cancelEndDate': 'Abunəlik sona çatır',
    'sub.cancelLastBilling': 'Son ödəniş',
    'sub.cancelYes': 'Bəli, ləğv et',
    'sub.cancelNo': 'Abunəliyi saxla',
    'sub.cancelledMsg': 'Abunəliyiniz ləğv edildi',
    'sub.cancelledEndInfo': 'Abunəliyiniz son çatdırılma tarixinədək aktiv qalacaq',

    // Order Tracking
    'tracking.title': 'Sifariş İzlənməsi',
    'tracking.placed': 'Sifariş tarixi',
    'tracking.inTransit': 'Yoldadır',
    'tracking.progress': 'Çatdırılma gedişatı',
    'tracking.deliveryDetails': 'Çatdırılma təfərrüatları',
    'tracking.pickupLocation': 'Götürmə yeri',
    'tracking.deliveryWindow': 'Çatdırılma vaxtı',
    'tracking.contactSupport': 'Dəstəklə əlaqə',
    'tracking.orderItems': 'Sifariş məhsulları',
    'tracking.pastOrders': 'Əvvəlki sifarişlər',
    'tracking.viewAll': 'Bütün sifarişlərə bax',
    'tracking.delivered': 'Çatdırıldı',
    'tracking.step.collected': 'Sifariş toplanıb',
    'tracking.step.collectedDesc': 'Məhsullar fermalardan toplanıb',
    'tracking.step.atHub': 'Emal mərkəzindədir',
    'tracking.step.atHubDesc': 'Soyuq anbarda çeşidlənib saxlanılır',
    'tracking.step.inTransit': 'Yoldadır',
    'tracking.step.inTransitDesc': 'Çatdırılma yerinə gedirdir',
    'tracking.step.delivered': 'Çatdırıldı',
    'tracking.step.deliveredDesc': 'Paket uğurla çatdırıldı',
    'tracking.expected': 'Gözlənilir:',
    'tracking.items': 'məhsul',
    'tracking.nasimi': 'Nəsimi Rayon Mərkəzi',
    'tracking.address': '28 May küçəsi, Bakı',
    'tracking.wednesday': 'Çərşənbə, 25 Mart',
    'tracking.window': '14:00 - 18:00',

    // Product Detail
    'product.title': 'Məhsul Təfərrüatları',
    'product.harvested': 'Yığılma tarixi',
    'product.nextDelivery': 'Növbəti çatdırılma',
    'product.farmTraceability': 'Ferma İzlənməsi',
    'product.experience': 'Təcrübə',
    'product.deliveryJourney': 'Çatdırılma Yolu',
    'product.step1Title': 'Fermadan toplama',
    'product.step1Desc': 'Bazar ertəsi axşamı - Məhsullar yerindən toplanır',
    'product.step2Title': 'Mərkəzdə emal',
    'product.step2Desc': 'Çərşənbə axşamı - Soyuq anbarda çeşidlənib qablaşdırılır',
    'product.step3Title': 'Sizə çatdırılma',
    'product.step3Desc': 'Çərşənbə - Təzə çatdırılma yerinizə',
    'product.addToCart': 'Səbətə əlavə et',
    'product.farmerProfile': 'Fermer Profili',
    'product.viewFarmerProfile': 'Fermerin profilinə bax',
    'product.farmerVerified': 'Təsdiqlənmiş Fermer',
    'product.farmerSince': 'Fəaliyyət müddəti',
    'product.farmerProducts': 'Məhsullar',
    'product.farmerRegion': 'Rayon',
    'product.farmerBio': 'Fermer haqqında',
    'product.closeFarmerProfile': 'Profili bağla',

    // Shelf life categories
    'category.sensitive': 'Tez xarab olan',
    'category.sensitiveDays': '1-2 gün',
    'category.sensitiveDesc': 'Yaşıl göyərti, giləmeyvə, süd',
    'category.medium': 'Orta müddət',
    'category.mediumDays': '3-5 gün',
    'category.mediumDesc': 'Tərəvəz və meyvələr',
    'category.durable': 'Uzun müddət',
    'category.durableDays': '7-14 gün',
    'category.durableDesc': 'Kök tərəvəzlər, yumurta, bal',

    // Farmer Dashboard
    'farmer.dashboard.title': 'Fermer Paneli',
    'farmer.dashboard.welcome': 'Xoş gəlmisiniz',
    'farmer.dashboard.verifiedFarmer': 'Təsdiqlənmiş fermer',
    'farmer.dashboard.nextCollection': 'Növbəti yığım nöqtəsi',
    'farmer.dashboard.thisWeek': 'Bu həftə',
    'farmer.dashboard.revenue': 'Gəlir',
    'farmer.dashboard.activeProducts': 'Aktiv məhsullar',
    'farmer.dashboard.pendingOrders': 'Gözləyən sifarişlər',
    'farmer.dashboard.upcomingDemand': 'Gözlənilən tələbat',
    'farmer.dashboard.manage': 'İdarə et',
    'farmer.dashboard.requested': 'Tələb olunur',
    'farmer.dashboard.yourCapacity': 'Sizin ehtiyatınız',
    'farmer.dashboard.deadline': 'Son tarix',
    'farmer.dashboard.available': 'Var',
    'farmer.dashboard.lowStock': 'Az qalıb',
    'farmer.dashboard.quickActions': 'Sürətli əməliyyatlar',
    'farmer.dashboard.addProduct': 'Yeni məhsul əlavə et',
    'farmer.dashboard.addProductDesc': 'Növbəti partiya üçün məhsul əlavə edin',
    'farmer.dashboard.viewEarnings': 'Gəlirə bax',
    'farmer.dashboard.viewEarningsDesc': 'Gəlir və ödənişləri izləyin',
    'farmer.dashboard.collectionPoints': 'Yığım nöqtələri',
    'farmer.dashboard.collectionPointsDesc': 'Çatdırılma yerlərini görün',
    'farmer.dashboard.recentDeliveries': 'Son çatdırılmalar',
    'farmer.dashboard.productsDelivered': 'məhsul çatdırılıb',
    'farmer.dashboard.paid': 'Ödənilib',
    'farmer.dashboard.tip': 'Məsləhət',
    'farmer.dashboard.tipText': 'Məhsullarınızın növbəti həftəlik çatdırılmaya daxil edilməsi üçün Bazar ertəsi günü son tarixdən əvvəl miqdarlarını yeniləyin.',

    // Farmer Profile
    'farmer.profile.title': 'Profilim',
    'farmer.profile.myProfile': 'Mənim Profilim',
    'farmer.profile.name': 'Ad',
    'farmer.profile.surname': 'Soyad',
    'farmer.profile.farmName': 'Ferma adı',
    'farmer.profile.phone': 'Telefon',
    'farmer.profile.region': 'Rayon',
    'farmer.profile.verified': 'Təsdiqlənmiş Fermer',
    'farmer.profile.since': 'Üzv olub',
    'farmer.profile.editProfile': 'Profili redaktə et',
    'farmer.profile.totalEarnings': 'Ümumi gəlir',
    'farmer.profile.deliveries': 'Çatdırılmalar',
    'farmer.profile.rating': 'Reytinq',
    'farmer.profile.premium': 'Fermer Premium',
    'farmer.profile.fromQ2': 'Q2-dən etibarən',
    'farmer.profile.premiumDesc': 'Axtarışda prioritet və məhsul analitikası əldə edin.',
    'farmer.profile.premiumPrice': '₼20 / ay',

    // Farmer Delivery/Shipping
    'farmer.delivery.title': 'Çatdırılma Cədvəli',
    'farmer.delivery.nextPickup': 'Növbəti toplama',
    'farmer.delivery.location': 'Məkan',
    'farmer.delivery.time': 'Vaxt',
    'farmer.delivery.packingTitle': 'Qablaşdırma Tələbləri',
    'farmer.delivery.packingBox': 'Güclü karton qutular istifadə edin (maks. 15kq)',
    'farmer.delivery.packingTemp': 'Həssas məhsulları soyuq saxlayın',
    'farmer.delivery.packingLabel': 'Məhsulları ad və çəki ilə etiketləyin',
    'farmer.delivery.packingTime': 'Toplanmadan 30 dəq əvvəl hazır olun',
    'farmer.delivery.driver': 'Sürücü',
    'farmer.delivery.vehicle': 'Nəqliyyat',
    'farmer.delivery.contactDriver': 'Sürücü ilə əlaqə',
    'farmer.delivery.upcoming': 'Yaxınlaşır',
    'farmer.delivery.batchInfo': 'Partiya Məlumatı',
    'farmer.delivery.currentBatch': 'Cari Partiya',
    'farmer.delivery.pendingItems': 'Gözləyən məhsullar',
    'farmer.delivery.status': 'Status',
    'farmer.delivery.monday': 'Bazar ertəsi, 18:00',
    'farmer.delivery.instructions': 'Göstərişlər',

    // Farmer Products
    'farmer.products.title': 'Məhsullarım',
    'farmer.products.active': 'Aktiv məhsullar',
    'farmer.products.expectedRevenue': 'Gözlənilən gəlir',
    'farmer.products.inDemand': 'Tələb olunan vahid',
    'farmer.products.addNew': 'Yeni məhsul əlavə et',
    'farmer.products.allTab': 'Bütün məhsullar',
    'farmer.products.inDemandTab': 'Tələbat var',
    'farmer.products.available': 'Mövcud',
    'farmer.products.demand': 'Tələbat',
    'farmer.products.potential': 'Gözlənilən gəlir:',
    'farmer.products.basedOn': 'Növbəti partiya üçün cari tələbata əsasən',
    'farmer.products.hubDemandTitle': 'Tələbat üçün təhvil nöqtəsi',
    'farmer.products.hubDemandDesc': 'Tələb olunan məhsulları hazırlayın və toplama vaxtından əvvəl bu mərkəzə təhvil verin. Sürücü məhsulları fermerlərdən ayrıca deyil, bu mərkəzdən götürəcək.',
    'farmer.products.stockAvailable': 'Mövcud ehtiyat:',
    'farmer.products.canFulfill': 'Yerinə yetirə bilərsiniz:',
    'farmer.products.revenue': 'Gəlir:',
    'farmer.products.addTitle': 'Yeni məhsul əlavə et',
    'farmer.products.namePlaceholder': 'məs., Pomidor',
    'farmer.products.nameLabel': 'Məhsul adı',
    'farmer.products.categoryLabel': 'Saxlanma müddəti',
    'farmer.products.sensitive': 'Həssas (1-2 gün)',
    'farmer.products.medium': 'Orta (3-5 gün)',
    'farmer.products.durable': 'Davamlı (7-14 gün)',
    'farmer.products.priceLabel': 'Qiymət (₼)',
    'farmer.products.unitLabel': 'Vahid',
    'farmer.products.quantityLabel': 'Mövcud miqdar',
    'farmer.products.add': 'Əlavə et',
    'farmer.products.activeStatus': 'Aktiv',
    'farmer.products.lowStock': 'Az qalıb',
    'farmer.products.ready': 'Hazırdır',
    'farmer.products.editTitle': 'Məhsulu redaktə et',
    'farmer.products.save': 'Dəyişiklikləri yadda saxla',
    'farmer.products.updated': 'Məhsul yeniləndi',
    'farmer.products.notFound': 'Məhsul tapılmadı',
    'farmer.products.deleteTitle': 'Elanı silmək istəyirsiniz?',
    'farmer.products.deleteDesc': 'Bu elan siyahıdan silinəcək və müştərilər artıq onu görməyəcəklər.',
    'farmer.products.delete': 'Elanı sil',
    'farmer.products.cancel': 'Ləğv et',

    // Farmer Earnings
    'farmer.earnings.title': 'Gəlirlər',
    'farmer.earnings.total': 'Ümumi gəlir (2026)',
    'farmer.earnings.thisWeek': 'Bu həftə',
    'farmer.earnings.pending': 'Gözləyən',
    'farmer.earnings.transactions': 'Əməliyyatlar',
    'farmer.earnings.weeklyStats': 'Həftəlik statistika',
    'farmer.earnings.delivered': 'Çatdırıldı:',
    'farmer.earnings.paid': 'Ödənilib',
    'farmer.earnings.pendingBadge': 'Gözləyir',
    'farmer.earnings.itemsBreakdown': 'Məhsul bölgüsü:',
    'farmer.earnings.downloadReceipt': 'Qəbzi yüklə',
    'farmer.earnings.monthlyTrend': 'Aylıq dinamika',
    'farmer.earnings.monthlyTotal': 'Aylıq cəm',
    'farmer.earnings.weekShort': 'H',
    'farmer.earnings.paymentSchedule': 'Ödəniş cədvəli',
    'farmer.earnings.paymentDesc': 'Ödənişlər uğurlu çatdırılmadan sonra 3-5 iş günü ərzində işlənir.',
    'farmer.earnings.nextPayment': 'Növbəti ödəniş: 28 Mart 2026-cı il üçün gözlənilir',
    'farmer.earnings.march': 'Mart 2026',

    // Customer Profile
    'customer.profile.title': 'Profilim',
    'customer.profile.name': 'Ad',
    'customer.profile.surname': 'Soyad',
    'customer.profile.address': 'Çatdırılma ünvanı',
    'customer.profile.phone': 'Telefon',
    'customer.profile.memberSince': 'Üzv olub',
    'customer.profile.editProfile': 'Profili redaktə et',
    'customer.profile.totalOrders': 'Ümumi sifarişlər',
    'customer.profile.totalSavings': 'Ümumi qənaət',
    'customer.profile.activeSubscriptions': 'Aktiv abunəliklər',

    // Admin Dashboard
    'admin.title': 'Admin Paneli',
    'admin.operations': 'Əməliyyat Mərkəzi',
    'admin.activeOrders': 'Aktiv sifarişlər',
    'admin.routesToday': 'Bu günün marşrutları',
    'admin.collectionPoints': 'Toplama nöqtələri',
    'admin.delivery': 'Çatdırılma:',
    'admin.ordersProcessed': 'Emal edilən sifarişlər',
    'admin.orderCutoff': 'Sifariş son tarixi:',
    'admin.inTransit': 'Yoldadır',
    'admin.urgentTasks': 'Təcili tapşırıqlar',
    'admin.collectionStatus': 'Sürücü üçün təhvil statusu',
    'admin.farmers': 'fermer',
    'admin.complete': 'Tamamlandı',
    'admin.collecting': 'Toplanır',
    'admin.collectionProgress': 'Toplama gedişatı',
    'admin.orders': 'sifariş',
    'admin.coldStorage': 'Soyuq Anbar',
    'admin.viewDetails': 'Ətraflı bax',
    'admin.todayOverview': 'Bu günün icmalı',
    'admin.totalOrders': 'Ümumi sifarişlər',
    'admin.activeRoutes': 'Aktiv marşrutlar',
    'admin.completed': 'Tamamlandı',
    'admin.pending': 'Gözləyir',
    'admin.temperature': 'Temperatur',
    'admin.optimal': 'Optimal',
    'admin.capacity': 'Tutum',
    'admin.urgentRoute': 'Marşrut 3 gecikir',
    'admin.urgentRouteDesc': 'M1 magistralında tıxac',
    'admin.urgentStorage': 'Soyuq anbar yoxlanışı tələb olunur',
    'admin.urgentStorageDesc': 'Həssas məhsullar bölməsi',
    'admin.driverReport': 'Sürücü bildirişi',
    'admin.taskStatus.pending': 'Gözləmədə',
    'admin.taskStatus.resolved': 'Həll edildi',
    'admin.taskStatus.cancelled': 'Ləğv edildi',
    'admin.statusChangedBy': 'Statusu dəyişdi',
    'admin.resolveTask': 'Tapşırığı həll et',
    'admin.taskUpdated': 'Tapşırıq statusu yeniləndi',
    'admin.noPendingTasks': 'Gözləyən təcili tapşırıq yoxdur',
    'admin.showManagedTasks': 'İdarə edilmiş tapşırıqlar',
    'admin.hideManagedTasks': 'İdarə edilmiş tapşırıqları gizlət',
    'admin.driverPickupDesc': 'Bu mərkəzdə sürücüyə təhvil veriləcək fermer sifarişləri',
    'admin.readyForDriver': 'Sürücü üçün hazır',
    'admin.awaitingFarmer': 'Fermer gözlənilir',
    'admin.quba': 'Quba Rayon Mərkəzi',
    'admin.shamakhi': 'Şamaxı Mərkəzi',
    'admin.gabala': 'Qəbələ Mərkəzi',
    'admin.lankaran': 'Lənkəran Mərkəzi',
    'admin.batch.batchId': 'Partiya ID',
    'admin.batch.routeDesc': 'Marşrut',
    'admin.route.id': 'Marşrut ID',
    'admin.route.routeDesc': 'Yol',
    'admin.profile.title': 'Admin profili',
    'admin.profile.operator': 'Əməliyyat administratoru',
    'admin.profile.role': 'Vəzifə',
    'admin.profile.roleValue': 'Əməliyyat administratoru',
    'admin.profile.phone': 'Telefon',
    'admin.profile.region': 'Əhatə dairəsi',
    'admin.profile.regionValue': 'Bütün toplama mərkəzləri',
    'admin.profile.memberSince': 'Komandaya qoşulub',
    'admin.profile.routesReviewed': 'Marşrut yoxlanılıb',
    'admin.profile.activeDrivers': 'Aktiv sürücü',
    'admin.profile.tasksResolved': 'Tapşırıq həll edilib',

    // Admin Storage
    'storage.title': 'Soyuq Anbar',
    'storage.overview': 'Anbar İcmalı',
    'storage.activeUnits': 'Aktiv bölmələr',
    'storage.totalItems': 'Ümumi məhsullar',
    'storage.capacity': 'Tutum',
    'storage.overviewTab': 'İcmal',
    'storage.monitoringTab': 'Monitorinq',
    'storage.products': 'Məhsullar',
    'storage.temperature': 'Temperatur',
    'storage.target': 'Hədəf:',
    'storage.humidity': 'Rütubət',
    'storage.optimalRange': 'Optimal diapazon',
    'storage.storedItems': 'Saxlanılan məhsullar:',
    'storage.lastCheck': 'Son yoxlama:',
    'storage.tempMonitoring': 'Temperatur Monitorinqi - COLD-01',
    'storage.systemStatus': 'Sistem Statusu',
    'storage.cooling': 'Soyutma Sistemi',
    'storage.airCirculation': 'Hava Dövriyyəsi',
    'storage.humidityControl': 'Rütubət Nəzarəti',
    'storage.backupPower': 'Ehtiyat Güc',
    'storage.active': 'Aktiv',
    'storage.normal': 'Normal',
    'storage.ready': 'Hazır',
    'storage.autoMonitoring': 'Avtomatik Monitorinq Aktivdir',
    'storage.autoMonitoringDesc': 'Temperatur və rütubət hər 5 dəqiqədən bir ölçülür. Dəyərlər optimal diapazondan kənara çıxarsa xəbərdarlıq göndəriləcək.',
    'storage.stableTemp': 'Temperatur optimal diapazon daxilindədir',
    'storage.sensitive': 'Həssas',
    'storage.medium': 'Orta',
    'storage.durable': 'Davamlı',
    'storage.items': 'məhsul',
    'storage.optimal': 'Optimal',
    'storage.humidityAlert': 'COLD-02 rütubəti aşağıdır',

    // Bottom navigation
    'nav.home': 'Ana səhifə',
    'nav.browse': 'Məhsullar',
    'nav.subscriptions': 'Abunəliklər',
    'nav.tracking': 'İzləmə',
    'nav.dashboard': 'Panel',
    'nav.products': 'Məhsullarım',
    'nav.deliveries': 'Çatdırılmalar',
    'nav.earnings': 'Gəlirlər',
    'nav.orders': 'Sifarişlər',
    'nav.routes': 'Marşrutlar',
    'nav.storage': 'Anbar',
    'nav.profile': 'Profil',
    'nav.vehicles': 'Nəqliyyat',
    'nav.driver': 'Sürücü',
    'cart.minOrder': 'Minimum sifariş: ₼22',
    'cart.minOrderNote': 'Sifariş vermək üçün minimum ₼22 olmalıdır',
    'cart.addMoreFor': 'Sifariş üçün daha',
    'cart.moreNeeded': 'əlavə edin',
    'cart.progressLabel': 'Minimum sifarişə doğru',
    'sub.individualPrice': 'Ayrı-ayrı qiymət',
    'sub.bundlePrice': 'Paket qiyməti',
    'sub.youSave': 'Qənaət edirsiniz',
    'sub.bestValue': 'Ən Sərfəli',
    'sub.goodDeal': 'Yaxşı Təklif',
    'sub.hotOffer': 'İsti Təklif',
    'sub.savePercent': 'qənaət',
    'sub.comparisonTitle': 'Qiymət Müqayisəsi',
    'sub.vsIndividual': 'Ayrı alış ilə müqayisədə',
    'driver.title': 'Sürücü Paneli',
    'driver.welcome': 'Xoş gəldiniz',
    'driver.myRoute': 'Mənim Marşrutum',
    'driver.availableRoutes': 'Mövcud Marşrutlar',
    'driver.claimRoute': 'Marşrutu Al',
    'driver.aiOptimized': 'Optimallaşdırılmış',
    'driver.aiRouteHeading': 'Süni intellekt ilə optimallaşdırılmış marşrutlar',
    'driver.aiRouteDesc': 'Marşrutlar süni intellekt tərəfindən müqayisə edilir və admin təsdiqindən sonra sürücüyə açılır.',
    'driver.adminApproved': 'Admin təsdiqləyib',
    'driver.adminPending': 'Admin təsdiqi gözlənilir',
    'driver.requestReview': 'Təsdiq gözlənilir',
    'driver.openMaps': 'Xəritədə aç',
    'driver.estimatedCost': 'Təxmini xərc',
    'driver.stops': 'dayanacaq',
    'driver.distance': 'məsafə',
    'driver.estimatedTime': 'Təxmini vaxt',
    'driver.efficiency': 'Effektivlik',
    'driver.startDelivery': 'Çatdırılmanı Başlat',
    'driver.markDelivered': 'Çatdırıldı Kimi İşarələ',
    'driver.nextStop': 'Növbəti Dayanacaq',
    'driver.allStops': 'Bütün Dayanacaqlar',
    'driver.completed': 'Tamamlandı',
    'driver.activeDelivery': 'Aktiv Çatdırılma',
    'driver.todayStats': 'Bu günün statistikası',
    'driver.routeSummary': 'Aktiv marşrut icmalı',
    'driver.completedStops': 'Tamamlanan',
    'driver.remainingOrders': 'Qalan sifariş',
    'driver.totalDistance': 'Ümumi məsafə',
    'driver.deliveries': 'Çatdırılmalar',
    'driver.earnings': 'Gəlir',
    'driver.orders': 'sifariş',
    'driver.km': 'km',
    'driver.noRoutes': 'Mövcud marşrut yoxdur',
    'driver.noRoutesDesc': 'Marşrutlar admin tərəfindən əlavə ediləcək',
    'driver.profile': 'Sürücü Profili',
    'driver.available': 'Mövcud',
    'driver.inProgress': 'Gedişatdadır',
    'vehicles.title': 'Nəqliyyat Vasitələri',
    'vehicles.allVehicles': 'Bütün Nəqliyyat',
    'vehicles.active': 'Aktiv',
    'vehicles.idle': 'Boş',
    'vehicles.maintenance': 'Texniki Baxış',
    'vehicles.driver': 'Sürücü',
    'vehicles.location': 'Məkan',
    'vehicles.orders': 'sifariş',
    'vehicles.route': 'Marşrut',
    'vehicles.speed': 'Sürət',
    'vehicles.assignDriver': 'Sürücü Təyin Et',
    'vehicles.trackLive': 'Canlı İzlə',
    'vehicles.liveTracking': 'Canlı İzləmə',
    'vehicles.type': 'Növ',
    'vehicles.plate': 'Dövlət nömrəsi',
    'vehicles.capacity': 'Tutum',
    'vehicles.lastUpdate': 'Son yeniləmə',
    'vehicles.fleet': 'Avtopark',
    'vehicles.totalDrivers': 'Sürücülər',
    'vehicles.activeNow': 'İndi aktiv',
    'vehicles.unassigned': 'Sürücüsüz',
    'vehicles.viewRoute': 'Marşruta bax',
    'vehicles.contactDriver': 'Sürücü ilə əlaqə',
    'vehicles.delayed': 'Gecikir',
    'vehicles.addVehicle': 'Yeni nəqliyyat əlavə et',
    'vehicles.fuel': 'Yanacaq',
    'vehicles.routeProgress': 'Marşrut gedişatı',
    'vehicles.gpsActive': 'Canlı GPS izləmə aktiv - yeniləmə hər 60s',
    'vehicles.currentStatus': 'Anlıq durum',
    'driver.dashboard': 'Sürücü paneli',
    'driver.openProfile': 'Profili aç',
    'driver.activeDriver': 'Aktiv sürücü',
    'driver.vehicle': 'Nəqliyyat',
    'driver.phone': 'Telefon',
    'driver.memberSince': 'Üzv olub',
    'driver.areas': 'Ərazilər',
    'driver.rating': 'Reytinq',
    'driver.onTime': 'Vaxtında',
    'driver.recentEarnings': 'Son gəlirlər',
    'driver.thisWeek': 'Bu həftə',
    'driver.lastWeek': 'Keçən həftə',
    'driver.paid': 'Ödənilib',
    'driver.navigationStart': 'Naviqasiyaya başla',
    'driver.stopsTitle': 'Dayanacaqlar',
    'driver.routeStops': 'Marşrut dayanacaqları',
    'driver.openSelected': 'Xəritədə aç',
    'driver.completeCurrent': 'Tamamla',
    'driver.stopCompleted': 'Dayanacaq tamamlandı',
    'driver.routeCompleted': 'Marşrut tamamlandı',
    'driver.routeCompletedDesc': 'Bütün dayanacaqlar uğurla tamamlanıb.',
    'driver.readyToStart': 'Başlamağa hazır',
    'driver.changeRouteStatus': 'Marşrut statusu',
    'driver.routeStatusUpdated': 'Marşrut statusu yeniləndi',
    'driver.routeApprovedReady': 'Marşrut admin tərəfindən təsdiqləndi',
    'driver.routeApprovedReadyDesc': 'Çatdırılmaya başlamaq üçün statusu aktivləşdirin.',
    'driver.priority': 'Prioritet',
    'driver.collectionOrders': 'Toplanacaq fermer sifarişləri',
    'driver.collectionsNav': 'Toplama',
    'driver.collectionReadiness': 'Təhvil hazırlığı',
    'driver.collectionReadinessDesc': 'Mərkəzdə götürülməyə hazır olan fermer sifarişləri',
    'driver.collectionHubDesc': 'Fermerlər məhsulları bu mərkəzə təhvil verir. Sürücü ayrı-ayrı fermalara getmədən bütün sifarişləri buradan götürür.',
    'driver.ready': 'Hazırdır',
    'driver.awaitingFarmer': 'Fermer gözlənilir',
    'driver.contactFarmer': 'Satıcıya zəng et',
    'driver.markReady': 'Hazır kimi qeyd et',
    'driver.markWaiting': 'Gözləməyə qaytar',
    'driver.collectionStatusUpdated': 'Təhvil statusu yeniləndi',
    'driver.reportIssue': 'Problem bildir',
    'driver.reportIssueDesc': 'Bildiriş admin panelində Təcili tapşırıqlar bölməsinə göndəriləcək.',
    'driver.issue.delay': 'Marşrutda gecikmə var',
    'driver.issue.pickup': 'Toplama nöqtəsində problem var',
    'driver.issue.vehicle': 'Nəqliyyat vasitəsində problem var',
    'driver.issueNote': 'Əlavə qeyd yazın',
    'driver.sendIssue': 'Adminə göndər',
    'driver.issueSent': 'Bildiriş adminə göndərildi',
    'farmer.products.messageLabel': 'Əlavə məlumat',
    'farmer.products.messagePlaceholder': 'Məhsul, qablaşdırma və ya toplama üçün qeydlər...',
    'farmer.earnings.weekLabel': 'Həftə',
    'customer.profile.personalDetails': 'Şəxsi məlumatlar',
    'customer.profile.recentOrders': 'Son sifarişlər',
    'customer.profile.premiumMember': 'Premium üzv',
    'customer.profile.premiumDesc': 'Premium üzvlər prioritet çatdırılma və abunə paketlərində əlavə endirimlər əldə edir.',
    'admin.routes.title': 'Marşrut İdarəetməsi',
    'admin.routes.active': 'Aktiv Marşrutlar',
    'admin.routes.scheduled': 'Planlaşdırılmış',
    'admin.routes.planning': 'Marşrut Planlaması',
    'admin.routes.planningDesc': 'Məkan klasterlərinə, kəndlərə və sifariş prioritetinə əsasən həftəlik marşrutları müqayisə edin.',
    'admin.routes.aiFindings': 'Süni intellekt nəticələri',
    'admin.routes.fastest': 'Daha sürətli',
    'admin.routes.cheaper': 'Daha ucuz',
    'admin.routes.recommended': 'Tövsiyə olunur',
    'admin.routes.approve': 'Təsdiqlə',
    'admin.routes.assignDriver': 'Sürücü təyin et',
    'admin.routes.viewDetails': 'Ətraflı bax',
    'admin.routes.createNew': 'Yeni marşrut yarat',
    'admin.routes.progress': 'Gedişat',
    'admin.routes.estimatedCompletion': 'Təxmini tamamlanma',
    'admin.routes.track': 'İzlə',
    'admin.routes.contactDriver': 'Sürücü ilə əlaqə',
    'admin.orders.title': 'Sifariş jurnalı',
    'admin.orders.logs': 'Bütün sifarişlər',
    'admin.orders.customer': 'Müştəri',
    'admin.orders.route': 'Marşrut',
    'admin.orders.batch': 'Partiya',
    'admin.orders.time': 'Vaxt',
    'admin.orders.status': 'Status',
    'catalog.selectCategory': 'Kateqoriya seçin',
    'catalog.selectProduct': 'Məhsul seçin',
    'catalog.category': 'Kateqoriya',
    'catalog.product': 'Məhsul',
    'ai.product.title': 'Süni intellekt analizi',
    'ai.product.heading': 'Məhsulu satışdan əvvəl yoxlayın',
    'ai.product.desc': 'Şəkil və məhsul məlumatlarına əsasən görünüş keyfiyyəti, təzəlik riski və satışa hazırlıq qiymətləndirilir.',
    'ai.product.photo': 'Məhsul şəkli',
    'ai.product.addPhoto': 'Şəkil çək və ya əlavə et',
    'ai.product.photoRequired': 'Analiz üçün məhsul şəkli əlavə edilməlidir.',
    'ai.product.quantity': 'Miqdar',
    'ai.product.price': 'Qiymət (₼)',
    'ai.product.location': 'Yerləşmə',
    'ai.product.analyze': 'Süni intellekt ilə analiz et',
    'ai.product.analyzing': 'Analiz edilir...',
    'ai.product.complete': 'Məhsul analizi tamamlandı',
    'ai.product.photoAdded': 'Şəkil əlavə edildi',
    'ai.product.result': 'Süni intellekt analizinin nəticəsi',
    'ai.product.saleReady': 'Satışa hazırdır',
    'ai.product.category': 'Yoxlanan məhsul',
    'ai.product.visualQuality': 'Görünüş keyfiyyəti',
    'ai.product.freshnessRisk': 'Təzəlik riski',
    'ai.product.good': 'Yaxşı',
    'ai.product.low': 'Aşağı',
    'ai.product.publish': 'Elanı yayımla',
    'ai.product.published': 'Məhsul elanı yayımlandı',
    'ai.product.publishFailed': 'Məhsulu yadda saxlamaq mümkün olmadı. Daha kiçik şəkil seçin.',
    'ai.product.open': 'Süni intellekt ilə məhsulu analiz et',
    'ai.product.continue': 'Məhsulu yoxla',
    'ai.product.stepDetails': 'Məhsul məlumatları',
    'ai.product.stepAnalysis': 'Süni intellekt analizi',
    'ai.product.summary': 'Məhsul məlumatları',
    'ai.product.edit': 'Düzəliş edin',
    'ai.route.title': 'Süni intellekt Marşrut Planlayıcısı',
    'ai.route.heading': 'Həftəlik marşrut tövsiyələri',
    'ai.route.desc': 'Sistem sifarişləri birləşdirir və operatorun təsdiqi üçün alternativ marşrutları müqayisə edir.',
    'ai.route.factors': 'Planlama meyarları',
    'ai.route.weeklyBatch': 'Həftəlik partiya',
    'ai.route.freshness': 'Təzəlik riski',
    'ai.route.distance': 'Məsafə',
    'ai.route.roadConditions': 'Yol şəraiti',
    'ai.route.urgency': 'Təcillik',
    'ai.route.nearbyOrders': 'Yaxın sifarişlər',
    'ai.route.recalculate': 'Tövsiyələri yenilə',
    'ai.route.recalculating': 'Yenidən hesablanır...',
    'ai.route.updated': 'Marşrut tövsiyələri yeniləndi',
    'ai.route.options': 'Marşrut variantları',
    'ai.route.selected': 'Seçilmiş marşrut',
    'ai.route.optimal': 'Optimal marşrut',
    'ai.route.efficiency': 'Səmərəlilik balı',
    'ai.route.approve': 'Marşrutu təsdiqlə',
    'ai.route.approved': 'Marşrut təsdiqləndi',
    'ai.route.open': 'Süni intellekt marşrut planlayıcısını aç',
    'ai.route.batchOrders': 'Partiya sifarişləri',
    'ai.route.batchOrdersDesc': 'Tövsiyəni faktiki həftəlik sifarişlərlə müqayisə edin.',
    'ai.route.orderCount': 'Sifariş',
    'ai.route.deliveryPoints': 'Təhvil nöqtəsi',
    'ai.route.sensitiveOrders': 'Həssas sifariş',
    'ai.route.recommendedChoice': 'Tövsiyə edilən seçim',
    'ai.route.whyRecommended': 'Niyə bu marşrut?',
    'ai.route.reason.capacity': 'Nəqliyyat tutumundan daha səmərəli istifadə edir.',
    'ai.route.reason.risk': 'Həssas məhsullar üçün daşınma riski daha aşağıdır.',
    'ai.route.reason.stops': 'Şəhərdaxili təhvil nöqtələrini birləşdirir.',
    'ai.route.compareAlternative': 'Alternativlə müqayisə',
    'ai.route.time': 'Vaxt',
    'ai.route.cost': 'Xərc',
    'ai.route.alternative': 'Alternativ',
    'ai.route.approveRecommended': 'Tövsiyə edilən marşrutu təsdiqlə',
  },
  en: {
    // Common
    'common.back': 'Back',
    'common.next': 'Next',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.viewAll': 'View all',
    'common.viewMore': 'View more',
    'common.close': 'Close',
    'common.cart': 'Cart',
    'common.profile': 'Profile',
    'common.per': 'per',
    'common.comingSoon': 'Coming soon',
    'common.more': 'more',
    'common.saved': 'Saved',
    'common.editProfile': 'Edit profile',
    'common.demoUpdated': 'Demo data updated',
    'common.detailsOpened': 'Details opened',

    // Customer Home
    'customer.home.title': 'KəndYol',
    'customer.home.freshFromFarm': 'Fresh from Farm',
    'customer.home.nextDelivery': 'Next delivery',
    'customer.home.orderCutoff': 'Order cutoff in:',
    'customer.home.hours': 'Hours',
    'customer.home.minutes': 'Minutes',
    'customer.home.seconds': 'Seconds',
    'customer.home.saveUpTo': 'Save up to',
    'customer.home.vsRetail': 'vs retail',
    'customer.home.farmFresh': 'Farm fresh',
    'customer.home.daysOld': 'days old',
    'customer.home.directFrom': 'Direct from',
    'customer.home.ruralFarms': 'Rural farms',
    'customer.home.subscriptionBoxes': 'Subscription Boxes',
    'customer.home.browseByShelfLife': 'Browse by Shelf Life',
    'customer.home.activeOrder': 'Active Order',
    'customer.home.orderInTransit': 'Order in Transit',
    'customer.home.arriving': 'Arriving',

    // Browse Products
    'browse.title': 'Browse Products',
    'browse.searchPlaceholder': 'Search products...',
    'browse.allProducts': 'All',
    'browse.available': 'products available',
    'browse.inCart': 'in cart',
    'browse.per': 'per',
    'browse.days': 'd',
    'browse.farmer': 'Farmer',

    // Product names & farms
    'product.organicTomatoes': 'Tomatoes',
    'product.freshSpinach': 'Fresh Spinach',
    'product.freeRangeEggs': 'Farm Eggs',
    'product.sweetPeppers': 'Sweet Peppers',
    'product.freshButter': 'Fresh Butter',
    'product.potatoes': 'Potatoes',
    'product.strawberries': 'Strawberries',
    'product.cucumbers': 'Cucumbers',
    'product.bunch': 'bunch',
    'product.dozen': 'dozen',
    'product.piece': 'piece',
    'product.kg': 'kg',

    // Cart
    'cart.title': 'Your Cart',
    'cart.nextDelivery': 'Next Delivery: Wednesday, March 25',
    'cart.orderCutoff': 'Order cutoff: Monday 11:59 PM (23h 45m remaining)',
    'cart.items': 'Items',
    'cart.deliveryMethod': 'Delivery Method',
    'cart.pickup': 'Pickup Point (Recommended)',
    'cart.pickupDesc': 'Collect from nearest hub location',
    'cart.free': 'Free',
    'cart.homeDelivery': 'Home Delivery',
    'cart.homeDeliveryDesc': '₼4 below ₼45. Free home delivery for orders of ₼45+.',
    'cart.savings': 'Your Savings',
    'cart.savingsDesc': 'Compared to retail prices - thanks to batch delivery!',
    'cart.subtotal': 'Subtotal',
    'cart.delivery': 'Delivery',
    'cart.retailPrice': 'Retail price comparison',
    'cart.yourSavings': 'Your savings',
    'cart.total': 'Total',
    'cart.checkout': 'Proceed to Checkout',
    'cart.empty': 'Your cart is empty',
    'cart.emptyDesc': 'Add some fresh products to get started',
    'cart.browseProducts': 'Browse Products',
    'cart.customize': 'Customize',
    'cart.youSaving': "You're Saving ₼{amount}",

    // Subscription boxes
    'boxes.vegetable': 'Vegetable Box',
    'boxes.dairy': 'Dairy Box',
    'boxes.meat': 'Meat Box',
    'boxes.custom': 'Custom Box',
    'boxes.items': 'items',
    'boxes.yourChoice': 'Your choice',
    'boxes.kg': 'kg',

    // Subscriptions
    'sub.title': 'Subscriptions',
    'sub.active': 'Active',
    'sub.available': 'Available Boxes',
    'sub.noActive': 'No Active Subscriptions',
    'sub.noActiveDesc': 'Subscribe to a box for regular deliveries',
    'sub.browseBoxes': 'Browse Boxes',
    'sub.weekly': 'Weekly',
    'sub.nextDelivery': 'Next delivery',
    'sub.week': 'week',
    'sub.included': 'Included items:',
    'sub.customizeTitle': 'Customize box',
    'sub.customizeDesc': 'Choose the items to keep in your next delivery.',
    'sub.customizeHint': 'Select at least one item.',
    'sub.customizeSaved': 'Box customized',
    'sub.activeStatus': 'Active subscription',
    'sub.paused': 'Paused',
    'sub.whySubscribe': 'Why Subscribe?',
    'sub.benefit1': 'Save up to 30% compared to one-time purchases',
    'sub.benefit2': 'Never run out of fresh produce',
    'sub.benefit3': 'Support local farmers with regular orders',
    'sub.benefit4': 'Skip or pause anytime',
    'sub.subscribeNow': 'Subscribe Now',
    'sub.nextBatch': 'Next Batch Delivery',
    'sub.nextBatchDesc': "Your subscription items will be included in Wednesday's delivery",
    'sub.cutoff': 'Order cutoff: Monday 11:59 PM',
    'sub.delivery': 'delivery',
    'sub.savings': 'savings',
    'sub.flexible': 'Flexible pricing',
    'sub.status.active': 'active',
    'sub.status.paused': 'paused',
    'sub.cancel': 'Cancel Subscription',
    'sub.cancelTitle': 'Cancel Subscription',
    'sub.cancelConfirm': 'Are you sure?',
    'sub.cancelDesc': 'This will cancel your subscription. No future payments will be charged.',
    'sub.cancelEndDate': 'Subscription ends on',
    'sub.cancelLastBilling': 'Last billing',
    'sub.cancelYes': 'Yes, Cancel',
    'sub.cancelNo': 'Keep Subscription',
    'sub.cancelledMsg': 'Subscription cancelled',
    'sub.cancelledEndInfo': 'Your subscription will remain active until the last delivery date',

    // Order Tracking
    'tracking.title': 'Order Tracking',
    'tracking.placed': 'Placed on',
    'tracking.inTransit': 'In Transit',
    'tracking.progress': 'Delivery Progress',
    'tracking.deliveryDetails': 'Delivery Details',
    'tracking.pickupLocation': 'Pickup Location',
    'tracking.deliveryWindow': 'Delivery Window',
    'tracking.contactSupport': 'Contact Support',
    'tracking.orderItems': 'Order Items',
    'tracking.pastOrders': 'Past Orders',
    'tracking.viewAll': 'View All Orders',
    'tracking.delivered': 'Delivered',
    'tracking.step.collected': 'Order Collected',
    'tracking.step.collectedDesc': 'Products collected from farms',
    'tracking.step.atHub': 'At Processing Hub',
    'tracking.step.atHubDesc': 'Sorted and stored in cold facility',
    'tracking.step.inTransit': 'In Transit',
    'tracking.step.inTransitDesc': 'On the way to delivery location',
    'tracking.step.delivered': 'Delivered',
    'tracking.step.deliveredDesc': 'Package delivered successfully',
    'tracking.expected': 'Expected:',
    'tracking.items': 'items',
    'tracking.nasimi': 'Nasimi District Hub',
    'tracking.address': '28 May Street, Baku',
    'tracking.wednesday': 'Wednesday, March 25',
    'tracking.window': '2:00 PM - 6:00 PM',

    // Product Detail
    'product.title': 'Product Details',
    'product.harvested': 'Harvested',
    'product.nextDelivery': 'Next Delivery',
    'product.farmTraceability': 'Farm Traceability',
    'product.experience': 'Experience',
    'product.deliveryJourney': 'Delivery Journey',
    'product.step1Title': 'Collection from Farm',
    'product.step1Desc': 'Monday evening - Products collected from',
    'product.step2Title': 'Processing at Hub',
    'product.step2Desc': 'Tuesday - Sorted and packed in cold storage',
    'product.step3Title': 'Delivery to You',
    'product.step3Desc': 'Wednesday - Fresh delivery to your location',
    'product.addToCart': 'Add to Cart',
    'product.farmerProfile': 'Farmer Profile',
    'product.viewFarmerProfile': "View Farmer's Profile",
    'product.farmerVerified': 'Verified Farmer',
    'product.farmerSince': 'Farming since',
    'product.farmerProducts': 'Products',
    'product.farmerRegion': 'Region',
    'product.farmerBio': 'About Farmer',
    'product.closeFarmerProfile': 'Close Profile',

    // Shelf life categories
    'category.sensitive': 'Sensitive Products',
    'category.sensitiveDays': '1-2 days',
    'category.sensitiveDesc': 'Leafy greens, berries, dairy',
    'category.medium': 'Medium Durability',
    'category.mediumDays': '3-5 days',
    'category.mediumDesc': 'Most vegetables, fruits',
    'category.durable': 'Durable Products',
    'category.durableDays': '7-14 days',
    'category.durableDesc': 'Root vegetables, eggs, honey',

    // Farmer Dashboard
    'farmer.dashboard.title': 'Farmer Dashboard',
    'farmer.dashboard.welcome': 'Welcome',
    'farmer.dashboard.verifiedFarmer': 'Verified Farmer',
    'farmer.dashboard.nextCollection': 'Next Collection Point',
    'farmer.dashboard.thisWeek': 'This Week',
    'farmer.dashboard.revenue': 'Revenue',
    'farmer.dashboard.activeProducts': 'Active Products',
    'farmer.dashboard.pendingOrders': 'Pending Orders',
    'farmer.dashboard.upcomingDemand': 'Upcoming Demand',
    'farmer.dashboard.manage': 'Manage',
    'farmer.dashboard.requested': 'Requested',
    'farmer.dashboard.yourCapacity': 'Your capacity',
    'farmer.dashboard.deadline': 'Deadline',
    'farmer.dashboard.available': 'Available',
    'farmer.dashboard.lowStock': 'Low Stock',
    'farmer.dashboard.quickActions': 'Quick Actions',
    'farmer.dashboard.addProduct': 'Add New Product',
    'farmer.dashboard.addProductDesc': 'List products for next batch',
    'farmer.dashboard.viewEarnings': 'View Earnings',
    'farmer.dashboard.viewEarningsDesc': 'Track your revenue and payments',
    'farmer.dashboard.collectionPoints': 'Collection Points',
    'farmer.dashboard.collectionPointsDesc': 'View delivery locations',
    'farmer.dashboard.recentDeliveries': 'Recent Deliveries',
    'farmer.dashboard.productsDelivered': 'products delivered',
    'farmer.dashboard.paid': 'Paid',
    'farmer.dashboard.tip': 'Tip',
    'farmer.dashboard.tipText': "Update your product quantities before Monday's cutoff to ensure your items are included in next week's batch delivery.",

    // Farmer Profile
    'farmer.profile.title': 'My Profile',
    'farmer.profile.myProfile': 'My Profile',
    'farmer.profile.name': 'Name',
    'farmer.profile.surname': 'Surname',
    'farmer.profile.farmName': 'Farm Name',
    'farmer.profile.phone': 'Phone',
    'farmer.profile.region': 'Region',
    'farmer.profile.verified': 'Verified Farmer',
    'farmer.profile.since': 'Member since',
    'farmer.profile.editProfile': 'Edit Profile',
    'farmer.profile.totalEarnings': 'Total Earnings',
    'farmer.profile.deliveries': 'Deliveries',
    'farmer.profile.rating': 'Rating',
    'farmer.profile.premium': 'Farmer Premium',
    'farmer.profile.fromQ2': 'From Q2',
    'farmer.profile.premiumDesc': 'Get search priority and product analytics.',
    'farmer.profile.premiumPrice': '₼20 / month',

    // Farmer Delivery/Shipping
    'farmer.delivery.title': 'Delivery Schedule',
    'farmer.delivery.nextPickup': 'Next Pickup',
    'farmer.delivery.location': 'Location',
    'farmer.delivery.time': 'Time',
    'farmer.delivery.packingTitle': 'Packaging Requirements',
    'farmer.delivery.packingBox': 'Use sturdy cardboard boxes (max. 15kg)',
    'farmer.delivery.packingTemp': 'Keep sensitive items cool',
    'farmer.delivery.packingLabel': 'Label products with name and weight',
    'farmer.delivery.packingTime': 'Be ready 30 min before pickup',
    'farmer.delivery.driver': 'Driver',
    'farmer.delivery.vehicle': 'Vehicle',
    'farmer.delivery.contactDriver': 'Contact Driver',
    'farmer.delivery.upcoming': 'Upcoming',
    'farmer.delivery.batchInfo': 'Batch Info',
    'farmer.delivery.currentBatch': 'Current Batch',
    'farmer.delivery.pendingItems': 'Pending items',
    'farmer.delivery.status': 'Status',
    'farmer.delivery.monday': 'Monday, 6:00 PM',
    'farmer.delivery.instructions': 'Instructions',

    // Farmer Products
    'farmer.products.title': 'My Products',
    'farmer.products.active': 'Active Products',
    'farmer.products.expectedRevenue': 'Expected Revenue',
    'farmer.products.inDemand': 'Units in Demand',
    'farmer.products.addNew': 'Add New Product',
    'farmer.products.allTab': 'All Products',
    'farmer.products.inDemandTab': 'In Demand',
    'farmer.products.available': 'Available',
    'farmer.products.demand': 'In Demand',
    'farmer.products.potential': 'Potential Revenue:',
    'farmer.products.basedOn': 'Based on current demand for next batch',
    'farmer.products.hubDemandTitle': 'Demand handoff point',
    'farmer.products.hubDemandDesc': 'Prepare requested products and deliver them to this hub before collection time. The driver collects from the hub, not from individual farms.',
    'farmer.products.stockAvailable': 'Your stock:',
    'farmer.products.canFulfill': 'Can fulfill:',
    'farmer.products.revenue': 'Revenue:',
    'farmer.products.addTitle': 'Add New Product',
    'farmer.products.namePlaceholder': 'e.g., Organic Tomatoes',
    'farmer.products.nameLabel': 'Product Name',
    'farmer.products.categoryLabel': 'Shelf Life Category',
    'farmer.products.sensitive': 'Sensitive (1-2 days)',
    'farmer.products.medium': 'Medium (3-5 days)',
    'farmer.products.durable': 'Durable (7-14 days)',
    'farmer.products.priceLabel': 'Price (₼)',
    'farmer.products.unitLabel': 'Unit',
    'farmer.products.quantityLabel': 'Available Quantity',
    'farmer.products.add': 'Add Product',
    'farmer.products.activeStatus': 'Active',
    'farmer.products.lowStock': 'Low',
    'farmer.products.ready': 'Ready',
    'farmer.products.editTitle': 'Edit product',
    'farmer.products.save': 'Save changes',
    'farmer.products.updated': 'Product updated',
    'farmer.products.notFound': 'Product not found',
    'farmer.products.deleteTitle': 'Delete this listing?',
    'farmer.products.deleteDesc': 'This listing will be removed and customers will no longer see it.',
    'farmer.products.delete': 'Delete listing',
    'farmer.products.cancel': 'Cancel',

    // Farmer Earnings
    'farmer.earnings.title': 'Earnings',
    'farmer.earnings.total': 'Total Earnings (2026)',
    'farmer.earnings.thisWeek': 'This Week',
    'farmer.earnings.pending': 'Pending',
    'farmer.earnings.transactions': 'Transactions',
    'farmer.earnings.weeklyStats': 'Weekly Stats',
    'farmer.earnings.delivered': 'Delivered:',
    'farmer.earnings.paid': 'Paid',
    'farmer.earnings.pendingBadge': 'Pending',
    'farmer.earnings.itemsBreakdown': 'Items breakdown:',
    'farmer.earnings.downloadReceipt': 'Download Receipt',
    'farmer.earnings.monthlyTrend': 'Monthly Trend',
    'farmer.earnings.monthlyTotal': 'Monthly total',
    'farmer.earnings.weekShort': 'W',
    'farmer.earnings.paymentSchedule': 'Payment Schedule',
    'farmer.earnings.paymentDesc': 'Payments are processed within 3-5 business days after successful delivery.',
    'farmer.earnings.nextPayment': 'Next payment: Expected March 28, 2026',
    'farmer.earnings.march': 'March 2026',

    // Customer Profile
    'customer.profile.title': 'My Profile',
    'customer.profile.name': 'Name',
    'customer.profile.surname': 'Surname',
    'customer.profile.address': 'Delivery Address',
    'customer.profile.phone': 'Phone',
    'customer.profile.memberSince': 'Member since',
    'customer.profile.editProfile': 'Edit Profile',
    'customer.profile.totalOrders': 'Total Orders',
    'customer.profile.totalSavings': 'Total Savings',
    'customer.profile.activeSubscriptions': 'Active Subscriptions',

    // Admin Dashboard
    'admin.title': 'Admin Dashboard',
    'admin.operations': 'Operations Center',
    'admin.activeOrders': 'Active Orders',
    'admin.routesToday': 'Routes Today',
    'admin.collectionPoints': 'Collection Points',
    'admin.delivery': 'Delivery:',
    'admin.ordersProcessed': 'Orders processed',
    'admin.orderCutoff': 'Order cutoff:',
    'admin.inTransit': 'In Transit',
    'admin.urgentTasks': 'Urgent Tasks',
    'admin.collectionStatus': 'Driver handoff status',
    'admin.farmers': 'farmers',
    'admin.complete': 'Complete',
    'admin.collecting': 'Collecting',
    'admin.collectionProgress': 'Collection progress',
    'admin.orders': 'orders',
    'admin.coldStorage': 'Cold Storage',
    'admin.viewDetails': 'View details',
    'admin.todayOverview': "Today's Overview",
    'admin.totalOrders': 'Total Orders',
    'admin.activeRoutes': 'Active Routes',
    'admin.completed': 'Completed',
    'admin.pending': 'Pending',
    'admin.temperature': 'Temperature',
    'admin.optimal': 'optimal',
    'admin.capacity': 'Capacity',
    'admin.urgentRoute': 'Route 3 delayed',
    'admin.urgentRouteDesc': 'Traffic on M1 highway',
    'admin.urgentStorage': 'Cold storage check needed',
    'admin.urgentStorageDesc': 'Sensitive items section',
    'admin.driverReport': 'Driver report',
    'admin.taskStatus.pending': 'Pending',
    'admin.taskStatus.resolved': 'Resolved',
    'admin.taskStatus.cancelled': 'Cancelled',
    'admin.statusChangedBy': 'Status changed by',
    'admin.resolveTask': 'Resolve task',
    'admin.taskUpdated': 'Task status updated',
    'admin.noPendingTasks': 'No urgent tasks are pending',
    'admin.showManagedTasks': 'Managed tasks',
    'admin.hideManagedTasks': 'Hide managed tasks',
    'admin.driverPickupDesc': 'Farmer orders to be handed over to the driver at this hub',
    'admin.readyForDriver': 'Ready for driver',
    'admin.awaitingFarmer': 'Awaiting farmer',
    'admin.quba': 'Quba District Hub',
    'admin.shamakhi': 'Shamakhi Hub',
    'admin.gabala': 'Gabala Hub',
    'admin.lankaran': 'Lankaran Hub',
    'admin.batch.batchId': 'Batch ID',
    'admin.batch.routeDesc': 'Route',
    'admin.route.id': 'Route ID',
    'admin.route.routeDesc': 'Path',
    'admin.profile.title': 'Admin Profile',
    'admin.profile.operator': 'Operations administrator',
    'admin.profile.role': 'Role',
    'admin.profile.roleValue': 'Operations administrator',
    'admin.profile.phone': 'Phone',
    'admin.profile.region': 'Coverage',
    'admin.profile.regionValue': 'All collection hubs',
    'admin.profile.memberSince': 'Joined team',
    'admin.profile.routesReviewed': 'Routes reviewed',
    'admin.profile.activeDrivers': 'Active drivers',
    'admin.profile.tasksResolved': 'Tasks resolved',

    // Admin Storage
    'storage.title': 'Cold Storage',
    'storage.overview': 'Storage Overview',
    'storage.activeUnits': 'Active Units',
    'storage.totalItems': 'Total Items',
    'storage.capacity': 'Capacity',
    'storage.overviewTab': 'Overview',
    'storage.monitoringTab': 'Monitoring',
    'storage.products': 'Products',
    'storage.temperature': 'Temperature',
    'storage.target': 'Target:',
    'storage.humidity': 'Humidity',
    'storage.optimalRange': 'Optimal range',
    'storage.storedItems': 'Stored items:',
    'storage.lastCheck': 'Last check:',
    'storage.tempMonitoring': 'Temperature Monitoring - COLD-01',
    'storage.systemStatus': 'System Status',
    'storage.cooling': 'Cooling System',
    'storage.airCirculation': 'Air Circulation',
    'storage.humidityControl': 'Humidity Control',
    'storage.backupPower': 'Backup Power',
    'storage.active': 'Active',
    'storage.normal': 'Normal',
    'storage.ready': 'Ready',
    'storage.autoMonitoring': 'Auto-Monitoring Active',
    'storage.autoMonitoringDesc': 'Temperature and humidity measured every 5 minutes. Alerts will be sent if values go outside optimal range.',
    'storage.stableTemp': 'Temperature within optimal range',
    'storage.sensitive': 'Sensitive',
    'storage.medium': 'Medium',
    'storage.durable': 'Durable',
    'storage.items': 'items',
    'storage.optimal': 'Optimal',
    'storage.humidityAlert': 'COLD-02 humidity low',

    // Bottom navigation
    'nav.home': 'Home',
    'nav.browse': 'Products',
    'nav.subscriptions': 'Subscriptions',
    'nav.tracking': 'Tracking',
    'nav.dashboard': 'Dashboard',
    'nav.products': 'My Products',
    'nav.deliveries': 'Deliveries',
    'nav.earnings': 'Earnings',
    'nav.orders': 'Orders',
    'nav.routes': 'Routes',
    'nav.storage': 'Storage',
    'nav.profile': 'Profile',
    'nav.vehicles': 'Vehicles',
    'nav.driver': 'Driver',
    'cart.minOrder': 'Minimum order: ₼22',
    'cart.minOrderNote': 'Minimum ₼22 required to place an order',
    'cart.addMoreFor': 'Add',
    'cart.moreNeeded': 'more to place order',
    'cart.progressLabel': 'Progress to minimum order',
    'sub.individualPrice': 'Individual price',
    'sub.bundlePrice': 'Bundle price',
    'sub.youSave': 'You save',
    'sub.bestValue': 'Best Value',
    'sub.goodDeal': 'Good Deal',
    'sub.hotOffer': 'Hot Offer',
    'sub.savePercent': 'off',
    'sub.comparisonTitle': 'Price Comparison',
    'sub.vsIndividual': 'Compared to buying separately',
    'driver.title': 'Driver Panel',
    'driver.welcome': 'Welcome',
    'driver.myRoute': 'My Route',
    'driver.availableRoutes': 'Available Routes',
    'driver.claimRoute': 'Claim Route',
    'driver.aiOptimized': 'AI Optimized',
    'driver.aiRouteHeading': 'AI-optimized routes',
    'driver.aiRouteDesc': 'Routes are compared by AI and released to drivers after admin approval.',
    'driver.adminApproved': 'Admin approved',
    'driver.adminPending': 'Awaiting admin approval',
    'driver.requestReview': 'Awaiting approval',
    'driver.openMaps': 'Open map',
    'driver.estimatedCost': 'Estimated cost',
    'driver.stops': 'stops',
    'driver.distance': 'distance',
    'driver.estimatedTime': 'Est. time',
    'driver.efficiency': 'Efficiency',
    'driver.startDelivery': 'Start Delivery',
    'driver.markDelivered': 'Mark as Delivered',
    'driver.nextStop': 'Next Stop',
    'driver.allStops': 'All Stops',
    'driver.completed': 'Completed',
    'driver.activeDelivery': 'Active Delivery',
    'driver.todayStats': "Today's Stats",
    'driver.routeSummary': 'Active route summary',
    'driver.completedStops': 'Completed',
    'driver.remainingOrders': 'Orders left',
    'driver.totalDistance': 'Total distance',
    'driver.deliveries': 'Deliveries',
    'driver.earnings': 'Earnings',
    'driver.orders': 'orders',
    'driver.km': 'km',
    'driver.noRoutes': 'No available routes',
    'driver.noRoutesDesc': 'Routes will be added by admin',
    'driver.profile': 'Driver Profile',
    'driver.available': 'Available',
    'driver.inProgress': 'In Progress',
    'vehicles.title': 'Vehicles',
    'vehicles.allVehicles': 'All Vehicles',
    'vehicles.active': 'Active',
    'vehicles.idle': 'Idle',
    'vehicles.maintenance': 'Maintenance',
    'vehicles.driver': 'Driver',
    'vehicles.location': 'Location',
    'vehicles.orders': 'Orders',
    'vehicles.route': 'Route',
    'vehicles.speed': 'Speed',
    'vehicles.assignDriver': 'Assign Driver',
    'vehicles.trackLive': 'Track Live',
    'vehicles.liveTracking': 'Live Tracking',
    'vehicles.type': 'Type',
    'vehicles.plate': 'License Plate',
    'vehicles.capacity': 'Capacity',
    'vehicles.lastUpdate': 'Last update',
    'vehicles.fleet': 'Fleet',
    'vehicles.totalDrivers': 'Total drivers',
    'vehicles.activeNow': 'Active now',
    'vehicles.unassigned': 'Unassigned',
    'vehicles.viewRoute': 'View Route',
    'vehicles.contactDriver': 'Contact Driver',
    'vehicles.delayed': 'Delayed',
    'vehicles.addVehicle': 'Add Vehicle',
    'vehicles.fuel': 'Fuel',
    'vehicles.routeProgress': 'Route progress',
    'vehicles.gpsActive': 'Live GPS tracking active - updates every 60s',
    'vehicles.currentStatus': 'Current status',
    'driver.dashboard': 'Driver dashboard',
    'driver.openProfile': 'Open profile',
    'driver.activeDriver': 'Active driver',
    'driver.vehicle': 'Vehicle',
    'driver.phone': 'Phone',
    'driver.memberSince': 'Member since',
    'driver.areas': 'Areas',
    'driver.rating': 'Rating',
    'driver.onTime': 'On time',
    'driver.recentEarnings': 'Recent earnings',
    'driver.thisWeek': 'This week',
    'driver.lastWeek': 'Last week',
    'driver.paid': 'Paid',
    'driver.navigationStart': 'Start navigation',
    'driver.stopsTitle': 'Stops',
    'driver.routeStops': 'Route stops',
    'driver.openSelected': 'Open map',
    'driver.completeCurrent': 'Complete',
    'driver.stopCompleted': 'Stop completed',
    'driver.routeCompleted': 'Route completed',
    'driver.routeCompletedDesc': 'All stops have been completed successfully.',
    'driver.readyToStart': 'Ready to start',
    'driver.changeRouteStatus': 'Route status',
    'driver.routeStatusUpdated': 'Route status updated',
    'driver.routeApprovedReady': 'Route approved by admin',
    'driver.routeApprovedReadyDesc': 'Activate the route when you are ready to begin delivery.',
    'driver.priority': 'Priority',
    'driver.collectionOrders': 'Farmer orders to collect',
    'driver.collectionsNav': 'Collection',
    'driver.collectionReadiness': 'Handoff readiness',
    'driver.collectionReadinessDesc': 'Farmer orders ready for pickup at the hub',
    'driver.collectionHubDesc': 'Farmers deliver products to this hub. The driver collects every order here instead of visiting individual farms.',
    'driver.ready': 'Ready',
    'driver.awaitingFarmer': 'Awaiting farmer',
    'driver.contactFarmer': 'Call farmer',
    'driver.markReady': 'Mark as ready',
    'driver.markWaiting': 'Mark as waiting',
    'driver.collectionStatusUpdated': 'Handoff status updated',
    'driver.reportIssue': 'Report an issue',
    'driver.reportIssueDesc': 'This report will appear under Urgent Tasks in the admin dashboard.',
    'driver.issue.delay': 'Route delay',
    'driver.issue.pickup': 'Pickup point issue',
    'driver.issue.vehicle': 'Vehicle issue',
    'driver.issueNote': 'Add a note',
    'driver.sendIssue': 'Send to admin',
    'driver.issueSent': 'Report sent to admin',
    'farmer.products.messageLabel': 'Additional message',
    'farmer.products.messagePlaceholder': 'Notes about product, packing, or pickup...',
    'farmer.earnings.weekLabel': 'Week',
    'customer.profile.personalDetails': 'Personal details',
    'customer.profile.recentOrders': 'Recent orders',
    'customer.profile.premiumMember': 'Premium member',
    'customer.profile.premiumDesc': 'Premium members get priority delivery and extra subscription box discounts.',
    'admin.routes.title': 'Route Management',
    'admin.routes.active': 'Active Routes',
    'admin.routes.scheduled': 'Scheduled',
    'admin.routes.planning': 'Route Planning',
    'admin.routes.planningDesc': 'Compare weekly routes based on village clusters, regions, and order priority.',
    'admin.routes.aiFindings': 'AI findings',
    'admin.routes.fastest': 'Faster',
    'admin.routes.cheaper': 'Cheaper',
    'admin.routes.recommended': 'Recommended',
    'admin.routes.approve': 'Approve',
    'admin.routes.assignDriver': 'Assign Driver',
    'admin.routes.viewDetails': 'View Details',
    'admin.routes.createNew': 'Create New Route',
    'admin.routes.progress': 'Progress',
    'admin.routes.estimatedCompletion': 'Estimated completion',
    'admin.routes.track': 'Track',
    'admin.routes.contactDriver': 'Contact driver',
    'admin.orders.title': 'Order Logs',
    'admin.orders.logs': 'All orders',
    'admin.orders.customer': 'Customer',
    'admin.orders.route': 'Route',
    'admin.orders.batch': 'Batch',
    'admin.orders.time': 'Time',
    'admin.orders.status': 'Status',
    'catalog.selectCategory': 'Select category',
    'catalog.selectProduct': 'Select product',
    'catalog.category': 'Category',
    'catalog.product': 'Product',
    'ai.product.title': 'Artificial intelligence analysis',
    'ai.product.heading': 'Check produce before listing',
    'ai.product.desc': 'Visual quality, freshness risk, and sale-readiness are evaluated from the photo and product details.',
    'ai.product.photo': 'Produce photo',
    'ai.product.addPhoto': 'Take or add photo',
    'ai.product.photoRequired': 'A produce photo is required for analysis.',
    'ai.product.quantity': 'Quantity',
    'ai.product.price': 'Price (₼)',
    'ai.product.location': 'Location',
    'ai.product.analyze': 'Analyze with artificial intelligence',
    'ai.product.analyzing': 'Analyzing...',
    'ai.product.complete': 'Product analysis complete',
    'ai.product.photoAdded': 'Photo added',
    'ai.product.result': 'Artificial intelligence analysis result',
    'ai.product.saleReady': 'Ready for sale',
    'ai.product.category': 'Recognized product',
    'ai.product.visualQuality': 'Visual quality',
    'ai.product.freshnessRisk': 'Freshness risk',
    'ai.product.good': 'Good',
    'ai.product.low': 'Low',
    'ai.product.publish': 'Publish listing',
    'ai.product.published': 'Product listing published',
    'ai.product.publishFailed': 'Could not save the product. Please choose a smaller photo.',
    'ai.product.open': 'Analyze product with artificial intelligence',
    'ai.product.continue': 'Check product',
    'ai.product.stepDetails': 'Product details',
    'ai.product.stepAnalysis': 'Artificial intelligence analysis',
    'ai.product.summary': 'Product details',
    'ai.product.edit': 'Edit details',
    'ai.route.title': 'AI Route Planner',
    'ai.route.heading': 'Weekly route recommendations',
    'ai.route.desc': 'The system groups orders and compares alternative routes for operator approval.',
    'ai.route.factors': 'Planning factors',
    'ai.route.weeklyBatch': 'Weekly batch',
    'ai.route.freshness': 'Freshness risk',
    'ai.route.distance': 'Distance',
    'ai.route.roadConditions': 'Road conditions',
    'ai.route.urgency': 'Urgency',
    'ai.route.nearbyOrders': 'Nearby orders',
    'ai.route.recalculate': 'Refresh recommendations',
    'ai.route.recalculating': 'Recalculating...',
    'ai.route.updated': 'Route recommendations updated',
    'ai.route.options': 'Route options',
    'ai.route.selected': 'Selected route',
    'ai.route.optimal': 'Optimal route',
    'ai.route.efficiency': 'Efficiency score',
    'ai.route.approve': 'Approve route',
    'ai.route.approved': 'Route approved',
    'ai.route.open': 'Open AI route planner',
    'ai.route.batchOrders': 'Batch orders',
    'ai.route.batchOrdersDesc': 'Compare the recommendation with the actual weekly orders.',
    'ai.route.orderCount': 'Orders',
    'ai.route.deliveryPoints': 'Delivery points',
    'ai.route.sensitiveOrders': 'Sensitive orders',
    'ai.route.recommendedChoice': 'Recommended choice',
    'ai.route.whyRecommended': 'Why this route?',
    'ai.route.reason.capacity': 'Uses vehicle capacity more efficiently.',
    'ai.route.reason.risk': 'Has lower transport risk for sensitive products.',
    'ai.route.reason.stops': 'Combines the city delivery points.',
    'ai.route.compareAlternative': 'Compare with alternative',
    'ai.route.time': 'Time',
    'ai.route.cost': 'Cost',
    'ai.route.alternative': 'Alternative',
    'ai.route.approveRecommended': 'Approve recommended route',
  },
  ru: {
    // Common
    'common.back': 'Назад',
    'common.next': 'Далее',
    'common.cancel': 'Отмена',
    'common.save': 'Сохранить',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.viewAll': 'Посмотреть все',
    'common.viewMore': 'Показать больше',
    'common.close': 'Закрыть',
    'common.cart': 'Корзина',
    'common.profile': 'Профиль',
    'common.per': 'за',
    'common.comingSoon': 'Скоро',
    'common.more': 'ещё',
    'common.saved': 'Сохранено',
    'common.editProfile': 'Редактировать профиль',
    'common.demoUpdated': 'Демо-данные обновлены',
    'common.detailsOpened': 'Детали открыты',

    // Customer Home
    'customer.home.title': 'КэндЙол',
    'customer.home.freshFromFarm': 'Свежее с фермы',
    'customer.home.nextDelivery': 'Следующая доставка',
    'customer.home.orderCutoff': 'Приём заказов до:',
    'customer.home.hours': 'Часы',
    'customer.home.minutes': 'Минуты',
    'customer.home.seconds': 'Секунды',
    'customer.home.saveUpTo': 'Экономия',
    'customer.home.vsRetail': 'дешевле рынка',
    'customer.home.farmFresh': 'Свежее с фермы',
    'customer.home.daysOld': 'дней назад собрано',
    'customer.home.directFrom': 'Напрямую',
    'customer.home.ruralFarms': 'с сельских ферм',
    'customer.home.subscriptionBoxes': 'Наборы по подписке',
    'customer.home.browseByShelfLife': 'По сроку хранения',
    'customer.home.activeOrder': 'Активный заказ',
    'customer.home.orderInTransit': 'Заказ в пути',
    'customer.home.arriving': 'Доставка:',

    // Browse Products
    'browse.title': 'Просмотр товаров',
    'browse.searchPlaceholder': 'Поиск товаров...',
    'browse.allProducts': 'Все',
    'browse.available': 'товаров доступно',
    'browse.inCart': 'в корзине',
    'browse.per': 'за',
    'browse.days': 'д',
    'browse.farmer': 'Фермер',

    // Product names & farms
    'product.organicTomatoes': 'Помидоры',
    'product.freshSpinach': 'Свежий шпинат',
    'product.freeRangeEggs': 'Деревенские яйца',
    'product.sweetPeppers': 'Сладкий перец',
    'product.freshButter': 'Свежее масло',
    'product.potatoes': 'Картофель',
    'product.strawberries': 'Клубника',
    'product.cucumbers': 'Огурцы',
    'product.bunch': 'пучок',
    'product.dozen': 'десяток',
    'product.piece': 'штука',
    'product.kg': 'кг',

    // Cart
    'cart.title': 'Ваша корзина',
    'cart.nextDelivery': 'Следующая доставка: Среда, 25 марта',
    'cart.orderCutoff': 'Дедлайн: Понедельник 23:59 (осталось 23ч 45м)',
    'cart.items': 'Товары',
    'cart.deliveryMethod': 'Способ доставки',
    'cart.pickup': 'Пункт выдачи (Рекомендуется)',
    'cart.pickupDesc': 'Получить в ближайшем пункте',
    'cart.free': 'Бесплатно',
    'cart.homeDelivery': 'Доставка на дом',
    'cart.homeDeliveryDesc': '₼4 для заказов до ₼45. Бесплатно для заказов от ₼45.',
    'cart.savings': 'Ваша экономия',
    'cart.savingsDesc': 'Дешевле рынка - благодаря пакетной доставке!',
    'cart.subtotal': 'Промежуточный итог',
    'cart.delivery': 'Доставка',
    'cart.retailPrice': 'Сравнение с рыночной ценой',
    'cart.yourSavings': 'Ваша экономия',
    'cart.total': 'Итого',
    'cart.checkout': 'Оформить заказ',
    'cart.empty': 'Ваша корзина пуста',
    'cart.emptyDesc': 'Добавьте свежие продукты для начала',
    'cart.browseProducts': 'Просмотр товаров',
    'cart.customize': 'Настроить',
    'cart.youSaving': 'Вы экономите ₼{amount}',

    // Subscription boxes
    'boxes.vegetable': 'Овощной набор',
    'boxes.dairy': 'Молочный набор',
    'boxes.meat': 'Мясной набор',
    'boxes.custom': 'Свой выбор',
    'boxes.items': 'товаров',
    'boxes.yourChoice': 'Ваш выбор',
    'boxes.kg': 'кг',

    // Subscriptions
    'sub.title': 'Подписки',
    'sub.active': 'Активные',
    'sub.available': 'Доступные наборы',
    'sub.noActive': 'Нет активных подписок',
    'sub.noActiveDesc': 'Подпишитесь на набор для регулярных доставок',
    'sub.browseBoxes': 'Смотреть наборы',
    'sub.weekly': 'Еженедельно',
    'sub.nextDelivery': 'Следующая доставка',
    'sub.week': 'неделя',
    'sub.included': 'Включённые товары:',
    'sub.customizeTitle': 'Настроить набор',
    'sub.customizeDesc': 'Выберите товары для следующей доставки.',
    'sub.customizeHint': 'Выберите хотя бы один товар.',
    'sub.customizeSaved': 'Набор настроен',
    'sub.activeStatus': 'Активная подписка',
    'sub.paused': 'Приостановлено',
    'sub.whySubscribe': 'Почему стоит подписаться?',
    'sub.benefit1': 'Экономьте до 30% по сравнению с разовыми покупками',
    'sub.benefit2': 'Никогда не оставайтесь без свежих продуктов',
    'sub.benefit3': 'Поддерживайте местных фермеров регулярными заказами',
    'sub.benefit4': 'Пропустите или приостановите в любое время',
    'sub.subscribeNow': 'Подписаться',
    'sub.nextBatch': 'Следующая пакетная доставка',
    'sub.nextBatchDesc': 'Ваши товары по подписке будут включены в доставку среды',
    'sub.cutoff': 'Дедлайн: Понедельник 23:59',
    'sub.delivery': 'доставка',
    'sub.savings': 'экономия',
    'sub.flexible': 'Гибкие цены',
    'sub.status.active': 'активна',
    'sub.status.paused': 'приостановлена',
    'sub.cancel': 'Отменить подписку',
    'sub.cancelTitle': 'Отменить подписку',
    'sub.cancelConfirm': 'Вы уверены?',
    'sub.cancelDesc': 'Это отменит вашу подписку. Будущие платежи не будут взиматься.',
    'sub.cancelEndDate': 'Подписка заканчивается',
    'sub.cancelLastBilling': 'Последний платёж',
    'sub.cancelYes': 'Да, отменить',
    'sub.cancelNo': 'Сохранить подписку',
    'sub.cancelledMsg': 'Подписка отменена',
    'sub.cancelledEndInfo': 'Ваша подписка останется активной до последней даты доставки',

    // Order Tracking
    'tracking.title': 'Отслеживание заказа',
    'tracking.placed': 'Дата заказа',
    'tracking.inTransit': 'В пути',
    'tracking.progress': 'Прогресс доставки',
    'tracking.deliveryDetails': 'Детали доставки',
    'tracking.pickupLocation': 'Место получения',
    'tracking.deliveryWindow': 'Время доставки',
    'tracking.contactSupport': 'Связаться с поддержкой',
    'tracking.orderItems': 'Товары заказа',
    'tracking.pastOrders': 'Прошлые заказы',
    'tracking.viewAll': 'Все заказы',
    'tracking.delivered': 'Доставлено',
    'tracking.step.collected': 'Заказ собран',
    'tracking.step.collectedDesc': 'Товары собраны с ферм',
    'tracking.step.atHub': 'На сортировочном центре',
    'tracking.step.atHubDesc': 'Отсортировано и хранится в холодильнике',
    'tracking.step.inTransit': 'В пути',
    'tracking.step.inTransitDesc': 'Едет к месту доставки',
    'tracking.step.delivered': 'Доставлено',
    'tracking.step.deliveredDesc': 'Посылка успешно доставлена',
    'tracking.expected': 'Ожидается:',
    'tracking.items': 'товаров',
    'tracking.nasimi': 'Насими районный центр',
    'tracking.address': 'ул. 28 мая, Баку',
    'tracking.wednesday': 'Среда, 25 марта',
    'tracking.window': '14:00 - 18:00',

    // Product Detail
    'product.title': 'Детали товара',
    'product.harvested': 'Дата сбора',
    'product.nextDelivery': 'Следующая доставка',
    'product.farmTraceability': 'Прослеживаемость фермы',
    'product.experience': 'Опыт',
    'product.deliveryJourney': 'Путь доставки',
    'product.step1Title': 'Сбор с фермы',
    'product.step1Desc': 'Понедельник вечером - Товары собраны с',
    'product.step2Title': 'Обработка на центре',
    'product.step2Desc': 'Вторник - Отсортировано и упаковано в холодильнике',
    'product.step3Title': 'Доставка вам',
    'product.step3Desc': 'Среда - Свежая доставка к вашему месту',
    'product.addToCart': 'Добавить в корзину',
    'product.farmerProfile': 'Профиль фермера',
    'product.viewFarmerProfile': 'Посмотреть профиль фермера',
    'product.farmerVerified': 'Верифицированный фермер',
    'product.farmerSince': 'Фермерство с',
    'product.farmerProducts': 'Товары',
    'product.farmerRegion': 'Район',
    'product.farmerBio': 'О фермере',
    'product.closeFarmerProfile': 'Закрыть профиль',

    // Shelf life categories
    'category.sensitive': 'Скоропортящиеся',
    'category.sensitiveDays': '1-2 дня',
    'category.sensitiveDesc': 'Зелень, ягоды, молочные продукты',
    'category.medium': 'Средний срок',
    'category.mediumDays': '3-5 дней',
    'category.mediumDesc': 'Большинство овощей и фруктов',
    'category.durable': 'Долгий срок',
    'category.durableDays': '7-14 дней',
    'category.durableDesc': 'Корнеплоды, яйца, мёд',

    // Farmer Dashboard
    'farmer.dashboard.title': 'Панель фермера',
    'farmer.dashboard.welcome': 'Добро пожаловать',
    'farmer.dashboard.verifiedFarmer': 'Верифицированный фермер',
    'farmer.dashboard.nextCollection': 'Следующий пункт сбора',
    'farmer.dashboard.thisWeek': 'На этой неделе',
    'farmer.dashboard.revenue': 'Доход',
    'farmer.dashboard.activeProducts': 'Активные товары',
    'farmer.dashboard.pendingOrders': 'Ожидающие заказы',
    'farmer.dashboard.upcomingDemand': 'Предстоящий спрос',
    'farmer.dashboard.manage': 'Управление',
    'farmer.dashboard.requested': 'Запрошено',
    'farmer.dashboard.yourCapacity': 'Ваш запас',
    'farmer.dashboard.deadline': 'Дедлайн',
    'farmer.dashboard.available': 'Есть',
    'farmer.dashboard.lowStock': 'Мало',
    'farmer.dashboard.quickActions': 'Быстрые действия',
    'farmer.dashboard.addProduct': 'Добавить товар',
    'farmer.dashboard.addProductDesc': 'Добавьте товары для следующей партии',
    'farmer.dashboard.viewEarnings': 'Посмотреть доходы',
    'farmer.dashboard.viewEarningsDesc': 'Отследите доходы и платежи',
    'farmer.dashboard.collectionPoints': 'Пункты сбора',
    'farmer.dashboard.collectionPointsDesc': 'Посмотреть места доставки',
    'farmer.dashboard.recentDeliveries': 'Последние доставки',
    'farmer.dashboard.productsDelivered': 'товаров доставлено',
    'farmer.dashboard.paid': 'Оплачено',
    'farmer.dashboard.tip': 'Совет',
    'farmer.dashboard.tipText': 'Обновите количество товаров до дедлайна в понедельник, чтобы ваши товары были включены в доставку следующей недели.',

    // Farmer Profile
    'farmer.profile.title': 'Мой профиль',
    'farmer.profile.myProfile': 'Мой профиль',
    'farmer.profile.name': 'Имя',
    'farmer.profile.surname': 'Фамилия',
    'farmer.profile.farmName': 'Название фермы',
    'farmer.profile.phone': 'Телефон',
    'farmer.profile.region': 'Район',
    'farmer.profile.verified': 'Верифицированный фермер',
    'farmer.profile.since': 'Участник с',
    'farmer.profile.editProfile': 'Редактировать профиль',
    'farmer.profile.totalEarnings': 'Общий доход',
    'farmer.profile.deliveries': 'Доставок',
    'farmer.profile.rating': 'Рейтинг',
    'farmer.profile.premium': 'Премиум для фермеров',
    'farmer.profile.fromQ2': 'Со II квартала',
    'farmer.profile.premiumDesc': 'Получите приоритет в поиске и аналитику товаров.',
    'farmer.profile.premiumPrice': '₼20 / месяц',

    // Farmer Delivery/Shipping
    'farmer.delivery.title': 'График доставки',
    'farmer.delivery.nextPickup': 'Следующий сбор',
    'farmer.delivery.location': 'Местонахождение',
    'farmer.delivery.time': 'Время',
    'farmer.delivery.packingTitle': 'Требования к упаковке',
    'farmer.delivery.packingBox': 'Используйте прочные картонные коробки (макс. 15 кг)',
    'farmer.delivery.packingTemp': 'Держите скоропортящиеся товары в холоде',
    'farmer.delivery.packingLabel': 'Маркируйте товары с названием и весом',
    'farmer.delivery.packingTime': 'Будьте готовы за 30 мин до сбора',
    'farmer.delivery.driver': 'Водитель',
    'farmer.delivery.vehicle': 'Транспорт',
    'farmer.delivery.contactDriver': 'Связаться с водителем',
    'farmer.delivery.upcoming': 'Предстоит',
    'farmer.delivery.batchInfo': 'Информация о партии',
    'farmer.delivery.currentBatch': 'Текущая партия',
    'farmer.delivery.pendingItems': 'Ожидающих товаров',
    'farmer.delivery.status': 'Статус',
    'farmer.delivery.monday': 'Понедельник, 18:00',
    'farmer.delivery.instructions': 'Инструкции',

    // Farmer Products
    'farmer.products.title': 'Мои товары',
    'farmer.products.active': 'Активные товары',
    'farmer.products.expectedRevenue': 'Ожидаемый доход',
    'farmer.products.inDemand': 'Единиц в спросе',
    'farmer.products.addNew': 'Добавить товар',
    'farmer.products.allTab': 'Все товары',
    'farmer.products.inDemandTab': 'Есть спрос',
    'farmer.products.available': 'В наличии',
    'farmer.products.demand': 'Спрос',
    'farmer.products.potential': 'Потенциальный доход:',
    'farmer.products.basedOn': 'На основе текущего спроса для следующей партии',
    'farmer.products.hubDemandTitle': 'Пункт передачи товаров',
    'farmer.products.hubDemandDesc': 'Подготовьте запрошенные товары и доставьте их в этот центр до времени сбора. Водитель забирает товары из центра, а не с отдельных ферм.',
    'farmer.products.stockAvailable': 'Ваш запас:',
    'farmer.products.canFulfill': 'Можете выполнить:',
    'farmer.products.revenue': 'Доход:',
    'farmer.products.addTitle': 'Добавить товар',
    'farmer.products.namePlaceholder': 'например, Органические помидоры',
    'farmer.products.nameLabel': 'Название товара',
    'farmer.products.categoryLabel': 'Срок хранения',
    'farmer.products.sensitive': 'Скоропортящийся (1-2 дня)',
    'farmer.products.medium': 'Средний (3-5 дней)',
    'farmer.products.durable': 'Долгий (7-14 дней)',
    'farmer.products.priceLabel': 'Цена (₼)',
    'farmer.products.unitLabel': 'Единица',
    'farmer.products.quantityLabel': 'Доступное количество',
    'farmer.products.add': 'Добавить',
    'farmer.products.activeStatus': 'Активно',
    'farmer.products.lowStock': 'Мало',
    'farmer.products.ready': 'Готово',
    'farmer.products.editTitle': 'Редактировать товар',
    'farmer.products.save': 'Сохранить изменения',
    'farmer.products.updated': 'Товар обновлён',
    'farmer.products.notFound': 'Товар не найден',
    'farmer.products.deleteTitle': 'Удалить объявление?',
    'farmer.products.deleteDesc': 'Объявление будет удалено, и покупатели больше не увидят его.',
    'farmer.products.delete': 'Удалить объявление',
    'farmer.products.cancel': 'Отмена',

    // Farmer Earnings
    'farmer.earnings.title': 'Доходы',
    'farmer.earnings.total': 'Общий доход (2026)',
    'farmer.earnings.thisWeek': 'На этой неделе',
    'farmer.earnings.pending': 'Ожидается',
    'farmer.earnings.transactions': 'Транзакции',
    'farmer.earnings.weeklyStats': 'Еженедельная статистика',
    'farmer.earnings.delivered': 'Доставлено:',
    'farmer.earnings.paid': 'Оплачено',
    'farmer.earnings.pendingBadge': 'Ожидается',
    'farmer.earnings.itemsBreakdown': 'Разбивка товаров:',
    'farmer.earnings.downloadReceipt': 'Скачать чек',
    'farmer.earnings.monthlyTrend': 'Месячная динамика',
    'farmer.earnings.monthlyTotal': 'Итого за месяц',
    'farmer.earnings.weekShort': 'Н',
    'farmer.earnings.paymentSchedule': 'График платежей',
    'farmer.earnings.paymentDesc': 'Платежи обрабатываются в течение 3-5 рабочих дней после успешной доставки.',
    'farmer.earnings.nextPayment': 'Следующий платёж: ожидается 28 марта 2026',
    'farmer.earnings.march': 'Март 2026',

    // Customer Profile
    'customer.profile.title': 'Мой профиль',
    'customer.profile.name': 'Имя',
    'customer.profile.surname': 'Фамилия',
    'customer.profile.address': 'Адрес доставки',
    'customer.profile.phone': 'Телефон',
    'customer.profile.memberSince': 'Участник с',
    'customer.profile.editProfile': 'Редактировать профиль',
    'customer.profile.totalOrders': 'Всего заказов',
    'customer.profile.totalSavings': 'Общая экономия',
    'customer.profile.activeSubscriptions': 'Активные подписки',

    // Admin Dashboard
    'admin.title': 'Панель администратора',
    'admin.operations': 'Центр операций',
    'admin.activeOrders': 'Активные заказы',
    'admin.routesToday': 'Маршруты сегодня',
    'admin.collectionPoints': 'Пункты сбора',
    'admin.delivery': 'Доставка:',
    'admin.ordersProcessed': 'Обработанные заказы',
    'admin.orderCutoff': 'Дедлайн заказов:',
    'admin.inTransit': 'В пути',
    'admin.urgentTasks': 'Срочные задачи',
    'admin.collectionStatus': 'Статус передачи водителю',
    'admin.farmers': 'фермеров',
    'admin.complete': 'Завершено',
    'admin.collecting': 'Сбор',
    'admin.collectionProgress': 'Прогресс сбора',
    'admin.orders': 'заказов',
    'admin.coldStorage': 'Холодный склад',
    'admin.viewDetails': 'Подробнее',
    'admin.todayOverview': 'Обзор дня',
    'admin.totalOrders': 'Всего заказов',
    'admin.activeRoutes': 'Активные маршруты',
    'admin.completed': 'Завершено',
    'admin.pending': 'Ожидается',
    'admin.temperature': 'Температура',
    'admin.optimal': 'оптимальная',
    'admin.capacity': 'Ёмкость',
    'admin.urgentRoute': 'Маршрут 3 задерживается',
    'admin.urgentRouteDesc': 'Пробка на трассе М1',
    'admin.urgentStorage': 'Требуется проверка холодного склада',
    'admin.urgentStorageDesc': 'Секция скоропортящихся товаров',
    'admin.driverReport': 'Сообщение водителя',
    'admin.taskStatus.pending': 'В ожидании',
    'admin.taskStatus.resolved': 'Решено',
    'admin.taskStatus.cancelled': 'Отменено',
    'admin.statusChangedBy': 'Статус изменил',
    'admin.resolveTask': 'Решить задачу',
    'admin.taskUpdated': 'Статус задачи обновлён',
    'admin.noPendingTasks': 'Нет ожидающих срочных задач',
    'admin.showManagedTasks': 'Обработанные задачи',
    'admin.hideManagedTasks': 'Скрыть обработанные задачи',
    'admin.driverPickupDesc': 'Заказы фермеров для передачи водителю в этом центре',
    'admin.readyForDriver': 'Готово для водителя',
    'admin.awaitingFarmer': 'Ожидается фермер',
    'admin.quba': 'Кубинский районный центр',
    'admin.shamakhi': 'Центр Шамахы',
    'admin.gabala': 'Центр Габалы',
    'admin.lankaran': 'Центр Лянкярана',
    'admin.batch.batchId': 'ID партии',
    'admin.batch.routeDesc': 'Маршрут',
    'admin.route.id': 'ID маршрута',
    'admin.route.routeDesc': 'Путь',
    'admin.profile.title': 'Профиль администратора',
    'admin.profile.operator': 'Администратор операций',
    'admin.profile.role': 'Роль',
    'admin.profile.roleValue': 'Администратор операций',
    'admin.profile.phone': 'Телефон',
    'admin.profile.region': 'Зона ответственности',
    'admin.profile.regionValue': 'Все центры сбора',
    'admin.profile.memberSince': 'В команде с',
    'admin.profile.routesReviewed': 'Проверено маршрутов',
    'admin.profile.activeDrivers': 'Активных водителей',
    'admin.profile.tasksResolved': 'Решено задач',

    // Admin Storage
    'storage.title': 'Холодный склад',
    'storage.overview': 'Обзор склада',
    'storage.activeUnits': 'Активные секции',
    'storage.totalItems': 'Всего товаров',
    'storage.capacity': 'Ёмкость',
    'storage.overviewTab': 'Обзор',
    'storage.monitoringTab': 'Мониторинг',
    'storage.products': 'Товары',
    'storage.temperature': 'Температура',
    'storage.target': 'Цель:',
    'storage.humidity': 'Влажность',
    'storage.optimalRange': 'Оптимальный диапазон',
    'storage.storedItems': 'Хранимые товары:',
    'storage.lastCheck': 'Последняя проверка:',
    'storage.tempMonitoring': 'Мониторинг температуры - COLD-01',
    'storage.systemStatus': 'Статус системы',
    'storage.cooling': 'Система охлаждения',
    'storage.airCirculation': 'Циркуляция воздуха',
    'storage.humidityControl': 'Контроль влажности',
    'storage.backupPower': 'Резервное питание',
    'storage.active': 'Активно',
    'storage.normal': 'Нормально',
    'storage.ready': 'Готово',
    'storage.autoMonitoring': 'Автоматический мониторинг активен',
    'storage.autoMonitoringDesc': 'Температура и влажность измеряются каждые 5 минут. Будет отправлено уведомление, если значения выйдут за пределы оптимального диапазона.',
    'storage.stableTemp': 'Температура в оптимальном диапазоне',
    'storage.sensitive': 'Скоропортящиеся',
    'storage.medium': 'Средний срок',
    'storage.durable': 'Долгий срок',
    'storage.items': 'товаров',
    'storage.optimal': 'Оптимально',
    'storage.humidityAlert': 'Влажность COLD-02 снижена',

    // Bottom navigation
    'nav.home': 'Главная',
    'nav.browse': 'Товары',
    'nav.subscriptions': 'Подписки',
    'nav.tracking': 'Отслеживание',
    'nav.dashboard': 'Панель',
    'nav.products': 'Мои товары',
    'nav.deliveries': 'Доставки',
    'nav.earnings': 'Доходы',
    'nav.orders': 'Заказы',
    'nav.routes': 'Маршруты',
    'nav.storage': 'Склад',
    'nav.profile': 'Профиль',
    'nav.vehicles': 'Транспорт',
    'nav.driver': 'Водитель',
    'cart.minOrder': 'Мин. заказ: ₼22',
    'cart.minOrderNote': 'Для оформления заказа минимум ₼22',
    'cart.addMoreFor': 'Добавьте ещё',
    'cart.moreNeeded': 'для оформления заказа',
    'cart.progressLabel': 'К минимальному заказу',
    'sub.individualPrice': 'Цена по-отдельности',
    'sub.bundlePrice': 'Цена набора',
    'sub.youSave': 'Вы экономите',
    'sub.bestValue': 'Лучшая цена',
    'sub.goodDeal': 'Выгодная сделка',
    'sub.hotOffer': 'Горячее предложение',
    'sub.savePercent': 'скидка',
    'sub.comparisonTitle': 'Сравнение цен',
    'sub.vsIndividual': 'По сравнению с покупкой по-отдельности',
    'driver.title': 'Панель водителя',
    'driver.welcome': 'Добро пожаловать',
    'driver.myRoute': 'Мой маршрут',
    'driver.availableRoutes': 'Доступные маршруты',
    'driver.claimRoute': 'Взять маршрут',
    'driver.aiOptimized': 'Оптимизирован ИИ',
    'driver.aiRouteHeading': 'Маршруты, оптимизированные ИИ',
    'driver.aiRouteDesc': 'Маршруты сравниваются ИИ и становятся доступны водителям после утверждения администратором.',
    'driver.adminApproved': 'Утверждено администратором',
    'driver.adminPending': 'Ожидает утверждения',
    'driver.requestReview': 'Ожидает утверждения',
    'driver.openMaps': 'Открыть карту',
    'driver.estimatedCost': 'Примерная стоимость',
    'driver.stops': 'остановок',
    'driver.distance': 'расстояние',
    'driver.estimatedTime': 'Прим. время',
    'driver.efficiency': 'Эффективность',
    'driver.startDelivery': 'Начать доставку',
    'driver.markDelivered': 'Отметить доставленным',
    'driver.nextStop': 'Следующая остановка',
    'driver.allStops': 'Все остановки',
    'driver.completed': 'Завершено',
    'driver.activeDelivery': 'Активная доставка',
    'driver.todayStats': 'Статистика дня',
    'driver.routeSummary': 'Сводка активного маршрута',
    'driver.completedStops': 'Завершено',
    'driver.remainingOrders': 'Осталось заказов',
    'driver.totalDistance': 'Общее расстояние',
    'driver.deliveries': 'Доставок',
    'driver.earnings': 'Доход',
    'driver.orders': 'заказов',
    'driver.km': 'км',
    'driver.noRoutes': 'Нет доступных маршрутов',
    'driver.noRoutesDesc': 'Маршруты будут добавлены администратором',
    'driver.profile': 'Профиль водителя',
    'driver.available': 'Свободен',
    'driver.inProgress': 'В работе',
    'vehicles.title': 'Транспортные средства',
    'vehicles.allVehicles': 'Все транспортные средства',
    'vehicles.active': 'Активно',
    'vehicles.idle': 'Свободно',
    'vehicles.maintenance': 'Тех. обслуживание',
    'vehicles.driver': 'Водитель',
    'vehicles.location': 'Местонахождение',
    'vehicles.orders': 'Заказы',
    'vehicles.route': 'Маршрут',
    'vehicles.speed': 'Скорость',
    'vehicles.assignDriver': 'Назначить водителя',
    'vehicles.trackLive': 'Следить онлайн',
    'vehicles.liveTracking': 'Прямое отслеживание',
    'vehicles.type': 'Тип',
    'vehicles.plate': 'Гос. номер',
    'vehicles.capacity': 'Вместимость',
    'vehicles.lastUpdate': 'Последнее обновление',
    'vehicles.fleet': 'Автопарк',
    'vehicles.totalDrivers': 'Всего водителей',
    'vehicles.activeNow': 'Активных сейчас',
    'vehicles.unassigned': 'Без водителя',
    'vehicles.viewRoute': 'Посмотреть маршрут',
    'vehicles.contactDriver': 'Связаться с водителем',
    'vehicles.delayed': 'Задерживается',
    'vehicles.addVehicle': 'Добавить транспорт',
    'vehicles.fuel': 'Топливо',
    'vehicles.routeProgress': 'Прогресс маршрута',
    'vehicles.gpsActive': 'GPS-отслеживание активно - обновление каждые 60 с',
    'vehicles.currentStatus': 'Текущий статус',
    'driver.dashboard': 'Панель водителя',
    'driver.openProfile': 'Открыть профиль',
    'driver.activeDriver': 'Активный водитель',
    'driver.vehicle': 'Транспорт',
    'driver.phone': 'Телефон',
    'driver.memberSince': 'Участник с',
    'driver.areas': 'Зоны',
    'driver.rating': 'Рейтинг',
    'driver.onTime': 'Вовремя',
    'driver.recentEarnings': 'Последние доходы',
    'driver.thisWeek': 'На этой неделе',
    'driver.lastWeek': 'На прошлой неделе',
    'driver.paid': 'Оплачено',
    'driver.navigationStart': 'Начать навигацию',
    'driver.stopsTitle': 'Остановки',
    'driver.routeStops': 'Остановки маршрута',
    'driver.openSelected': 'Открыть карту',
    'driver.completeCurrent': 'Завершить',
    'driver.stopCompleted': 'Остановка завершена',
    'driver.routeCompleted': 'Маршрут завершён',
    'driver.routeCompletedDesc': 'Все остановки успешно завершены.',
    'driver.readyToStart': 'Готов к старту',
    'driver.changeRouteStatus': 'Статус маршрута',
    'driver.routeStatusUpdated': 'Статус маршрута обновлён',
    'driver.routeApprovedReady': 'Маршрут утверждён администратором',
    'driver.routeApprovedReadyDesc': 'Активируйте маршрут, когда будете готовы начать доставку.',
    'driver.priority': 'Приоритет',
    'driver.collectionOrders': 'Заказы фермеров для сбора',
    'driver.collectionsNav': 'Сбор',
    'driver.collectionReadiness': 'Готовность к передаче',
    'driver.collectionReadinessDesc': 'Заказы фермеров, готовые к выдаче в центре',
    'driver.collectionHubDesc': 'Фермеры доставляют товары в этот центр. Водитель забирает все заказы здесь, не посещая отдельные фермы.',
    'driver.ready': 'Готово',
    'driver.awaitingFarmer': 'Ожидается фермер',
    'driver.contactFarmer': 'Позвонить фермеру',
    'driver.markReady': 'Отметить готовым',
    'driver.markWaiting': 'Вернуть в ожидание',
    'driver.collectionStatusUpdated': 'Статус передачи обновлён',
    'driver.reportIssue': 'Сообщить о проблеме',
    'driver.reportIssueDesc': 'Сообщение появится в разделе срочных задач панели администратора.',
    'driver.issue.delay': 'Задержка маршрута',
    'driver.issue.pickup': 'Проблема в пункте сбора',
    'driver.issue.vehicle': 'Проблема с транспортом',
    'driver.issueNote': 'Добавьте примечание',
    'driver.sendIssue': 'Отправить администратору',
    'driver.issueSent': 'Сообщение отправлено администратору',
    'farmer.products.messageLabel': 'Дополнительное сообщение',
    'farmer.products.messagePlaceholder': 'Заметки о товаре, упаковке или сборе...',
    'farmer.earnings.weekLabel': 'Неделя',
    'customer.profile.personalDetails': 'Личные данные',
    'customer.profile.recentOrders': 'Последние заказы',
    'customer.profile.premiumMember': 'Премиум-участник',
    'customer.profile.premiumDesc': 'Премиум-участники получают приоритетную доставку и дополнительные скидки на наборы.',
    'admin.routes.title': 'Управление маршрутами',
    'admin.routes.active': 'Активные маршруты',
    'admin.routes.scheduled': 'Запланированные',
    'admin.routes.planning': 'Планирование маршрутов',
    'admin.routes.planningDesc': 'Сравните недельные маршруты по кластерам деревень, регионам и приоритету заказов.',
    'admin.routes.aiFindings': 'Выводы ИИ',
    'admin.routes.fastest': 'Быстрее',
    'admin.routes.cheaper': 'Дешевле',
    'admin.routes.recommended': 'Рекомендуется',
    'admin.routes.approve': 'Утвердить',
    'admin.routes.assignDriver': 'Назначить водителя',
    'admin.routes.viewDetails': 'Подробнее',
    'admin.routes.createNew': 'Создать маршрут',
    'admin.routes.progress': 'Прогресс',
    'admin.routes.estimatedCompletion': 'Ожидаемое завершение',
    'admin.routes.track': 'Отследить',
    'admin.routes.contactDriver': 'Связаться с водителем',
    'admin.orders.title': 'Журнал заказов',
    'admin.orders.logs': 'Все заказы',
    'admin.orders.customer': 'Клиент',
    'admin.orders.route': 'Маршрут',
    'admin.orders.batch': 'Партия',
    'admin.orders.time': 'Время',
    'admin.orders.status': 'Статус',
    'catalog.selectCategory': 'Выберите категорию',
    'catalog.selectProduct': 'Выберите товар',
    'catalog.category': 'Категория',
    'catalog.product': 'Товар',
    'ai.product.title': 'ИИ-анализ продукта',
    'ai.product.heading': 'Проверьте продукт перед публикацией',
    'ai.product.desc': 'По фото и данным продукта оцениваются внешний вид, риск потери свежести и готовность к продаже.',
    'ai.product.photo': 'Фото продукта',
    'ai.product.addPhoto': 'Снять или добавить фото',
    'ai.product.photoRequired': 'Для анализа необходимо добавить фото продукта.',
    'ai.product.quantity': 'Количество',
    'ai.product.price': 'Цена (₼)',
    'ai.product.location': 'Местонахождение',
    'ai.product.analyze': 'Анализировать с ИИ',
    'ai.product.analyzing': 'Анализ...',
    'ai.product.complete': 'Анализ продукта завершён',
    'ai.product.photoAdded': 'Фото добавлено',
    'ai.product.result': 'Результат ИИ-анализа',
    'ai.product.saleReady': 'Готово к продаже',
    'ai.product.category': 'Распознанный продукт',
    'ai.product.visualQuality': 'Внешний вид',
    'ai.product.freshnessRisk': 'Риск потери свежести',
    'ai.product.good': 'Хорошо',
    'ai.product.low': 'Низкий',
    'ai.product.publish': 'Опубликовать товар',
    'ai.product.published': 'Товар опубликован',
    'ai.product.publishFailed': 'Не удалось сохранить товар. Выберите фото меньшего размера.',
    'ai.product.open': 'Анализировать продукт с ИИ',
    'ai.product.continue': 'Перейти к ИИ-анализу',
    'ai.product.stepDetails': 'Данные продукта',
    'ai.product.stepAnalysis': 'ИИ-анализ',
    'ai.product.summary': 'Данные продукта',
    'ai.product.edit': 'Изменить',
    'ai.route.title': 'ИИ-планировщик маршрутов',
    'ai.route.heading': 'Еженедельные рекомендации маршрутов',
    'ai.route.desc': 'Система группирует заказы и сравнивает варианты маршрутов для утверждения оператором.',
    'ai.route.factors': 'Факторы планирования',
    'ai.route.weeklyBatch': 'Еженедельная партия',
    'ai.route.freshness': 'Риск свежести',
    'ai.route.distance': 'Расстояние',
    'ai.route.roadConditions': 'Дорожные условия',
    'ai.route.urgency': 'Срочность',
    'ai.route.nearbyOrders': 'Ближайшие заказы',
    'ai.route.recalculate': 'Обновить рекомендации',
    'ai.route.recalculating': 'Пересчёт...',
    'ai.route.updated': 'Рекомендации маршрутов обновлены',
    'ai.route.options': 'Варианты маршрута',
    'ai.route.selected': 'Выбранный маршрут',
    'ai.route.optimal': 'Оптимальный маршрут',
    'ai.route.efficiency': 'Оценка эффективности',
    'ai.route.approve': 'Утвердить маршрут',
    'ai.route.approved': 'Маршрут утверждён',
    'ai.route.open': 'Открыть ИИ-планировщик',
    'ai.route.batchOrders': 'Заказы партии',
    'ai.route.batchOrdersDesc': 'Сравните рекомендацию с фактическими заказами недели.',
    'ai.route.orderCount': 'Заказы',
    'ai.route.deliveryPoints': 'Пункты доставки',
    'ai.route.sensitiveOrders': 'Чувствительные заказы',
    'ai.route.recommendedChoice': 'Рекомендуемый выбор',
    'ai.route.whyRecommended': 'Почему этот маршрут?',
    'ai.route.reason.capacity': 'Эффективнее использует вместимость транспорта.',
    'ai.route.reason.risk': 'Снижает риск перевозки чувствительных продуктов.',
    'ai.route.reason.stops': 'Объединяет городские пункты доставки.',
    'ai.route.compareAlternative': 'Сравнение с альтернативой',
    'ai.route.time': 'Время',
    'ai.route.cost': 'Стоимость',
    'ai.route.alternative': 'Альтернатива',
    'ai.route.approveRecommended': 'Утвердить рекомендуемый маршрут',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('az');

  const t = (key: string): string => {
    const langTranslations = translations[language] as Record<string, string>;
    return langTranslations[key] || translations['az'][key as keyof typeof translations['az']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
